((((type . "package_declaration")
   (name . "global")
   (beg-point . 71)
   (end-point . 1949))
  . 70)
 (((type . "package_declaration")
   (name . "global")
   (beg-point . 71)
   (end-point . 1949))
  . 89)
 (((type . "package_declaration")
   (name . "global")
   (beg-point . 71)
   (end-point . 1949))
  . 1337)
 (nil . 1411)
 (((type . "package_declaration")
   (name . "global")
   (beg-point . 71)
   (end-point . 1949))
  . 1950))
