((#s(xref-match-item
     #("end package global_sim;" 12 22
       (face vhdl-ext-xref-match-face))
     #s(xref-file-location "global_sim.vhd" 62 12)
     10)
    #s(xref-match-item
       #("end package body global_sim;" 17 27
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "global_sim.vhd" 264 17)
       10)
    #s(xref-match-item
       #("use xil_defaultlib.global_sim.all;" 19 29
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "tb_axi_if_converter.vhd" 6 19)
       10))
 (#s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 81 20)
		     9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 88 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 95 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 105 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 112 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 124 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 135 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 146 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 157 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 168 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 179 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 190 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 201 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 212 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 222 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 232 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 246 20)
		       9)
    #s(xref-match-item "        wait for (5*AXI_CLK_T);" #s(xref-file-location "global_sim.vhd" 258 20)
		       9)
    #s(xref-match-item "    clk <= (not clk and not stop_clock) after AXI_CLK_T/2;" #s(xref-file-location "tb_axi_if_converter.vhd" 496 46)
		       9)
    #s(xref-match-item "            wait for (5*AXI_CLK_T);" #s(xref-file-location "tb_axi_if_converter.vhd" 534 24)
		       9)
    #s(xref-match-item "            wait for (5*AXI_CLK_T);" #s(xref-file-location "tb_axi_if_converter.vhd" 536 24)
		       9)
    #s(xref-match-item
       #("            wait for AXI_CLK_T;" 21 30
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "tb_axi_if_converter.vhd" 544 21)
       9)
    #s(xref-match-item
       #("                wait for AXI_CLK_T;" 25 34
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "tb_axi_if_converter.vhd" 547 25)
       9)
    #s(xref-match-item
       #("            wait for AXI_CLK_T;" 21 30
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "tb_axi_if_converter.vhd" 550 21)
       9)
    #s(xref-match-item "        wait for (50*AXI_CLK_T);" #s(xref-file-location "tb_axi_if_converter.vhd" 568 21)
		       9)
    #s(xref-match-item "        wait for (50*AXI_CLK_T);" #s(xref-file-location "tb_axi_if_converter.vhd" 572 21)
		       9)
    #s(xref-match-item "        wait for (500*AXI_CLK_T);" #s(xref-file-location "tb_axi_if_converter.vhd" 580 22)
		       9))
 (#s(xref-match-item
     #("    end procedure read_control_reg;" 18 34
       (face vhdl-ext-xref-match-face))
     #s(xref-file-location "global_sim.vhd" 82 18)
     16)
    #s(xref-match-item
       #("        read_control_reg(s_bfm_in_r, s_bfm_out_r);" 8 24
	 (face vhdl-ext-xref-match-face))
       #s(xref-file-location "tb_axi_if_converter.vhd" 557 8)
       16)))
