(("Entity"
  ("axi_if_converter" . #<marker at 1057 in hierarchy.vhd>)
  ("pattern_counter" . #<marker at 34613 in hierarchy.vhd>)
  ("clk_div" . #<marker at 36169 in hierarchy.vhd>)
  ("clk_sync" . #<marker at 37205 in hierarchy.vhd>)
  ("input_buffer" . #<marker at 38138 in hierarchy.vhd>)
  ("core_fsm" . #<marker at 60224 in hierarchy.vhd>)
  ("core_converter" . #<marker at 64758 in hierarchy.vhd>)
  ("axi_lite_regs" . #<marker at 98535 in hierarchy.vhd>)
  ("axi_lite_master" . #<marker at 123512 in hierarchy.vhd>))
 ("Architecture"
  ("RTL of axi_if_converter" . #<marker at 10723 in hierarchy.vhd>)
  ("RTL of pattern_counter" . #<marker at 35214 in hierarchy.vhd>)
  ("RTL of clk_div" . #<marker at 36433 in hierarchy.vhd>)
  ("RTL of clk_sync" . #<marker at 37446 in hierarchy.vhd>)
  ("RTL of input_buffer" . #<marker at 40351 in hierarchy.vhd>)
  ("RTL of core_fsm" . #<marker at 61028 in hierarchy.vhd>)
  ("RTL of core_converter" . #<marker at 69266 in hierarchy.vhd>)
  ("RTL of axi_lite_regs" . #<marker at 101110 in hierarchy.vhd>)
  ("RTL of axi_lite_master" . #<marker at 125536 in hierarchy.vhd>))
 ("Component"
  ("blk_mem_gen_0" . #<marker at 40388 in hierarchy.vhd>))
 ("Process"
  ("pattern_count_proc" . #<marker at 35434 in hierarchy.vhd>)
  ("div_proc" . #<marker at 36548 in hierarchy.vhd>)
  ("clk_fs_sync_proc" . #<marker at 37521 in hierarchy.vhd>)
  ("axi_bram_logic_l" . #<marker at 50812 in hierarchy.vhd>)
  ("axi_bram_logic_r" . #<marker at 51698 in hierarchy.vhd>)
  ("read_to_output_reg_l" . #<marker at 52584 in hierarchy.vhd>)
  ("read_to_output_reg_r" . #<marker at 53994 in hierarchy.vhd>)
  ("bram_ptr_pos_l_proc" . #<marker at 55404 in hierarchy.vhd>)
  ("bram_ptr_pos_r_proc" . #<marker at 56126 in hierarchy.vhd>)
  ("output_reg_loading_l" . #<marker at 56849 in hierarchy.vhd>)
  ("output_reg_loading_r" . #<marker at 58068 in hierarchy.vhd>)
  ("delay_output_reg_valid_l" . #<marker at 59286 in hierarchy.vhd>)
  ("delay_output_reg_valid_r" . #<marker at 59687 in hierarchy.vhd>)
  ("fsm_axi_full" . #<marker at 61556 in hierarchy.vhd>)
  ("fsm_proc" . #<marker at 76572 in hierarchy.vhd>)
  ("read_burst_size_calc_proc" . #<marker at 82080 in hierarchy.vhd>)
  ("araddr_proc" . #<marker at 83922 in hierarchy.vhd>)
  ("arvalid_proc" . #<marker at 84527 in hierarchy.vhd>)
  ("arlen_proc" . #<marker at 85474 in hierarchy.vhd>)
  ("rdata_counter_proc" . #<marker at 85831 in hierarchy.vhd>)
  ("rdata_total_counter_proc" . #<marker at 86307 in hierarchy.vhd>)
  ("r_done_proc" . #<marker at 86951 in hierarchy.vhd>)
  ("write_burst_size_calc_proc" . #<marker at 87405 in hierarchy.vhd>)
  ("awaddr_proc" . #<marker at 89360 in hierarchy.vhd>)
  ("strobe_burst_proc" . #<marker at 89964 in hierarchy.vhd>)
  ("awlen_proc" . #<marker at 91130 in hierarchy.vhd>)
  ("awvalid_proc" . #<marker at 91487 in hierarchy.vhd>)
  ("wdata_counter_proc" . #<marker at 92437 in hierarchy.vhd>)
  ("wdata_total_counter_proc" . #<marker at 92960 in hierarchy.vhd>)
  ("wlast_proc" . #<marker at 94158 in hierarchy.vhd>)
  ("bready_proc" . #<marker at 95404 in hierarchy.vhd>)
  ("request_edge_detection_proc" . #<marker at 96261 in hierarchy.vhd>)
  ("pattern_cnt_proc" . #<marker at 96672 in hierarchy.vhd>)
  ("axi_awready_proc" . #<marker at 106461 in hierarchy.vhd>)
  ("axi_awaddr_proc" . #<marker at 107105 in hierarchy.vhd>)
  ("axi_wready_proc" . #<marker at 107728 in hierarchy.vhd>)
  ("axi_bvalid_proc" . #<marker at 108527 in hierarchy.vhd>)
  ("axi_arready_proc" . #<marker at 109526 in hierarchy.vhd>)
  ("axi_rvalid_proc" . #<marker at 110615 in hierarchy.vhd>)
  ("axi_rdata_proc" . #<marker at 111274 in hierarchy.vhd>)
  ("address_decoding_proc" . #<marker at 111713 in hierarchy.vhd>)
  ("read_write_regs_proc" . #<marker at 113841 in hierarchy.vhd>)
  ("read_only_regs_proc" . #<marker at 118978 in hierarchy.vhd>)
  ("control_reg_signals_proc" . #<marker at 120717 in hierarchy.vhd>)
  ("soft_reset_out_proc" . #<marker at 121328 in hierarchy.vhd>)
  ("mm2s_proc" . #<marker at 122001 in hierarchy.vhd>)
  ("master_lite_proc" . #<marker at 122652 in hierarchy.vhd>)
  ("awvalid_proc" . #<marker at 127054 in hierarchy.vhd>)
  ("wvalid_proc" . #<marker at 127550 in hierarchy.vhd>)
  ("awaddr_proc" . #<marker at 128039 in hierarchy.vhd>)
  ("wdata_proc" . #<marker at 128396 in hierarchy.vhd>)
  ("bready_proc" . #<marker at 128911 in hierarchy.vhd>)
  ("arvalid_proc" . #<marker at 129397 in hierarchy.vhd>)
  ("rready_proc" . #<marker at 129897 in hierarchy.vhd>)
  ("araddr_proc" . #<marker at 130383 in hierarchy.vhd>)
  ("do_read" . #<marker at 130738 in hierarchy.vhd>)
  ("error_proc" . #<marker at 131530 in hierarchy.vhd>))
 ("Procedure"
  ("bram_logic" . #<marker at 40965 in hierarchy.vhd>)
  ("bram_logic_rst" . #<marker at 41671 in hierarchy.vhd>)
  ("read_to_output_reg_logic" . #<marker at 42049 in hierarchy.vhd>)
  ("read_to_output_reg_logic_rst" . #<marker at 43495 in hierarchy.vhd>)
  ("bram_pointer_position_calc" . #<marker at 44212 in hierarchy.vhd>)
  ("bram_pointer_position_rst" . #<marker at 44695 in hierarchy.vhd>)
  ("load_output_reg" . #<marker at 45004 in hierarchy.vhd>)
  ("load_output_reg_rst" . #<marker at 46113 in hierarchy.vhd>)
  ("add_bit" . #<marker at 105600 in hierarchy.vhd>)
  ("add_out_sigH" . #<marker at 120772 in hierarchy.vhd>))
 ("Function"
  ("clogb2" . #<marker at 69305 in hierarchy.vhd>))
 ("Instance"
  ("axi_lite_regs" . #<marker at 15173 in hierarchy.vhd>)
  ("input_buffer" . #<marker at 17680 in hierarchy.vhd>)
  ("core_converter" . #<marker at 20902 in hierarchy.vhd>)
  ("core_converter" . #<marker at 25055 in hierarchy.vhd>)
  ("axi_lite_master" . #<marker at 29209 in hierarchy.vhd>)
  ("clk_div" . #<marker at 31109 in hierarchy.vhd>)
  ("clk_sync" . #<marker at 31407 in hierarchy.vhd>)
  ("pattern_counter" . #<marker at 31660 in hierarchy.vhd>)
  ("pattern_counter" . #<marker at 32241 in hierarchy.vhd>)
  ("core_fsm" . #<marker at 32822 in hierarchy.vhd>)
  ("core_fsm" . #<marker at 33646 in hierarchy.vhd>)
  ("BUFG" . #<marker at 36991 in hierarchy.vhd>)
  ("blk_mem_gen_0" . #<marker at 48667 in hierarchy.vhd>)
  ("blk_mem_gen_0" . #<marker at 49125 in hierarchy.vhd>)))
