-- Hierarchy generated by `vhdl-ext'

-- * axi_if_converter
-- ** axi_lite_regs
-- ** input_buffer
-- *** blk_mem_gen_0
-- **** blk_mem_gen_v8_4_2
-- ***** blk_mem_gen_v8_4_2_synth
-- *** blk_mem_gen_0
-- **** blk_mem_gen_v8_4_2
-- ***** blk_mem_gen_v8_4_2_synth
-- ** core_converter
-- ** core_converter
-- ** axi_lite_master
-- ** clk_div
-- *** BUFG
-- ** clk_sync
-- ** pattern_counter
-- ** pattern_counter
-- ** core_fsm
-- ** core_fsm


-- * Buffer local variables
-- Local Variables:
-- eval: (vhdl-mode 1)
-- eval: (vhdl-ext-hierarchy-outshine-nav-mode 1)
-- End:
