-- Hierarchy generated by `vhdl-ext'

-- * instances
-- ** block0
-- ** block0
-- ** block0
-- ** block1
-- ** block1
-- ** block1
-- ** block1
-- ** gen_block1(0):for-generate
-- *** block1
-- ** gen_block1(1):for-generate
-- *** block1
-- ** gen_block1(2):for-generate
-- *** block1
-- ** gen_block1(3):for-generate
-- *** block1


-- * Buffer local variables
-- Local Variables:
-- eval: (vhdl-mode 1)
-- eval: (vhdl-ext-hierarchy-outshine-nav-mode 1)
-- End:
