#s(hash-table test equal data
	      (("clk" :file "../files/common/axi_if_converter.vhd" :line 12)
	       (:type "signal_interface_declaration" :desc "        clk        : in std_logic;" :col 8 :parent "axi_if_converter")
	       ("resetn" :file "../files/common/axi_if_converter.vhd" :line 13)
	       (:type "signal_interface_declaration" :desc "        resetn     : in std_logic;" :col 8 :parent "axi_if_converter")
	       ("clk_fs_ext" :file "../files/common/axi_if_converter.vhd" :line 14)
	       (:type "signal_interface_declaration" :desc "        clk_fs_ext : in std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_aclk" :file "../files/common/axi_if_converter.vhd" :line 17)
	       (:type "signal_interface_declaration" :desc "        s_axi_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_aresetn" :file "../files/common/axi_if_converter.vhd" :line 18)
	       (:type "signal_interface_declaration" :desc "        s_axi_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_awaddr" :file "../files/common/axi_if_converter.vhd" :line 19)
	       (:type "signal_interface_declaration" :desc "        s_axi_awaddr  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_awprot" :file "../files/common/axi_if_converter.vhd" :line 20)
	       (:type "signal_interface_declaration" :desc "        s_axi_awprot  : in  std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_awvalid" :file "../files/common/axi_if_converter.vhd" :line 21)
	       (:type "signal_interface_declaration" :desc "        s_axi_awvalid : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_awready" :file "../files/common/axi_if_converter.vhd" :line 22)
	       (:type "signal_interface_declaration" :desc "        s_axi_awready : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_wdata" :file "../files/common/axi_if_converter.vhd" :line 23)
	       (:type "signal_interface_declaration" :desc "        s_axi_wdata   : in  std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_wstrb" :file "../files/common/axi_if_converter.vhd" :line 24)
	       (:type "signal_interface_declaration" :desc "        s_axi_wstrb   : in  std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_wvalid" :file "../files/common/axi_if_converter.vhd" :line 25)
	       (:type "signal_interface_declaration" :desc "        s_axi_wvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_wready" :file "../files/common/axi_if_converter.vhd" :line 26)
	       (:type "signal_interface_declaration" :desc "        s_axi_wready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_bresp" :file "../files/common/axi_if_converter.vhd" :line 27)
	       (:type "signal_interface_declaration" :desc "        s_axi_bresp   : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_bvalid" :file "../files/common/axi_if_converter.vhd" :line 28)
	       (:type "signal_interface_declaration" :desc "        s_axi_bvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_bready" :file "../files/common/axi_if_converter.vhd" :line 29)
	       (:type "signal_interface_declaration" :desc "        s_axi_bready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_araddr" :file "../files/common/axi_if_converter.vhd" :line 30)
	       (:type "signal_interface_declaration" :desc "        s_axi_araddr  : in  std_logic_vector(C_S_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_arprot" :file "../files/common/axi_if_converter.vhd" :line 31)
	       (:type "signal_interface_declaration" :desc "        s_axi_arprot  : in  std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_arvalid" :file "../files/common/axi_if_converter.vhd" :line 32)
	       (:type "signal_interface_declaration" :desc "        s_axi_arvalid : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_arready" :file "../files/common/axi_if_converter.vhd" :line 33)
	       (:type "signal_interface_declaration" :desc "        s_axi_arready : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_rdata" :file "../files/common/axi_if_converter.vhd" :line 34)
	       (:type "signal_interface_declaration" :desc "        s_axi_rdata   : out std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_rresp" :file "../files/common/axi_if_converter.vhd" :line 35)
	       (:type "signal_interface_declaration" :desc "        s_axi_rresp   : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axi_rvalid" :file "../files/common/axi_if_converter.vhd" :line 36)
	       (:type "signal_interface_declaration" :desc "        s_axi_rvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axi_rready" :file "../files/common/axi_if_converter.vhd" :line 37)
	       (:type "signal_interface_declaration" :desc "        s_axi_rready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_aclk" :file "../files/common/axi_if_converter.vhd" :line 40)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 41)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_tdata" :file "../files/common/axi_if_converter.vhd" :line 42)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_tdata   : in  std_logic_vector(63 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_tvalid" :file "../files/common/axi_if_converter.vhd" :line 43)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_tvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_tkeep" :file "../files/common/axi_if_converter.vhd" :line 44)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_tkeep   : in  std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_tlast" :file "../files/common/axi_if_converter.vhd" :line 45)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_tlast   : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_lch_tready" :file "../files/common/axi_if_converter.vhd" :line 46)
	       (:type "signal_interface_declaration" :desc "        s_axis_lch_tready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_aclk" :file "../files/common/axi_if_converter.vhd" :line 48)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 49)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_tdata" :file "../files/common/axi_if_converter.vhd" :line 50)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_tdata   : in  std_logic_vector(63 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_tvalid" :file "../files/common/axi_if_converter.vhd" :line 51)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_tvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_tkeep" :file "../files/common/axi_if_converter.vhd" :line 52)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_tkeep   : in  std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_tlast" :file "../files/common/axi_if_converter.vhd" :line 53)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_tlast   : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("s_axis_rch_tready" :file "../files/common/axi_if_converter.vhd" :line 54)
	       (:type "signal_interface_declaration" :desc "        s_axis_rch_tready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_aclk" :file "../files/common/axi_if_converter.vhd" :line 57)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 58)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tdata" :file "../files/common/axi_if_converter.vhd" :line 59)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tdata   : out std_logic_vector(63 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tvalid" :file "../files/common/axi_if_converter.vhd" :line 60)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tkeep" :file "../files/common/axi_if_converter.vhd" :line 61)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tkeep   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tlast" :file "../files/common/axi_if_converter.vhd" :line 62)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tlast   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tready" :file "../files/common/axi_if_converter.vhd" :line 63)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_lch_tdest" :file "../files/common/axi_if_converter.vhd" :line 64)
	       (:type "signal_interface_declaration" :desc "        m_axis_lch_tdest   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_aclk" :file "../files/common/axi_if_converter.vhd" :line 66)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 67)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tdata" :file "../files/common/axi_if_converter.vhd" :line 68)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tdata   : out std_logic_vector(63 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tvalid" :file "../files/common/axi_if_converter.vhd" :line 69)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tkeep" :file "../files/common/axi_if_converter.vhd" :line 70)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tkeep   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tlast" :file "../files/common/axi_if_converter.vhd" :line 71)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tlast   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tready" :file "../files/common/axi_if_converter.vhd" :line 72)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axis_rch_tdest" :file "../files/common/axi_if_converter.vhd" :line 73)
	       (:type "signal_interface_declaration" :desc "        m_axis_rch_tdest   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_aclk" :file "../files/common/axi_if_converter.vhd" :line 76)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 77)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awid" :file "../files/common/axi_if_converter.vhd" :line 78)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awid    : out std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awaddr" :file "../files/common/axi_if_converter.vhd" :line 79)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awaddr  : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awlen" :file "../files/common/axi_if_converter.vhd" :line 80)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awlen   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awsize" :file "../files/common/axi_if_converter.vhd" :line 81)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awsize  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awburst" :file "../files/common/axi_if_converter.vhd" :line 82)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awburst : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awlock" :file "../files/common/axi_if_converter.vhd" :line 83)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awlock  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awcache" :file "../files/common/axi_if_converter.vhd" :line 84)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awcache : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awprot" :file "../files/common/axi_if_converter.vhd" :line 85)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awqos" :file "../files/common/axi_if_converter.vhd" :line 86)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awqos   : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awuser" :file "../files/common/axi_if_converter.vhd" :line 87)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awuser  : out std_logic_vector(C_M_AXI_AWUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awvalid" :file "../files/common/axi_if_converter.vhd" :line 88)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_awready" :file "../files/common/axi_if_converter.vhd" :line 89)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_awready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wdata" :file "../files/common/axi_if_converter.vhd" :line 90)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wdata   : out std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wstrb" :file "../files/common/axi_if_converter.vhd" :line 91)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wstrb   : out std_logic_vector(C_M_AXI_DATA_WIDTH/8-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wlast" :file "../files/common/axi_if_converter.vhd" :line 92)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wlast   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wuser" :file "../files/common/axi_if_converter.vhd" :line 93)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wuser   : out std_logic_vector(C_M_AXI_WUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wvalid" :file "../files/common/axi_if_converter.vhd" :line 94)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_wready" :file "../files/common/axi_if_converter.vhd" :line 95)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_wready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_bid" :file "../files/common/axi_if_converter.vhd" :line 96)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_bid     : in  std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_bresp" :file "../files/common/axi_if_converter.vhd" :line 97)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_bresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_buser" :file "../files/common/axi_if_converter.vhd" :line 98)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_buser   : in  std_logic_vector(C_M_AXI_BUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_bvalid" :file "../files/common/axi_if_converter.vhd" :line 99)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_bvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_bready" :file "../files/common/axi_if_converter.vhd" :line 100)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_bready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arid" :file "../files/common/axi_if_converter.vhd" :line 101)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arid    : out std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_araddr" :file "../files/common/axi_if_converter.vhd" :line 102)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_araddr  : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arlen" :file "../files/common/axi_if_converter.vhd" :line 103)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arlen   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arsize" :file "../files/common/axi_if_converter.vhd" :line 104)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arsize  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arburst" :file "../files/common/axi_if_converter.vhd" :line 105)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arburst : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arlock" :file "../files/common/axi_if_converter.vhd" :line 106)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arlock  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arcache" :file "../files/common/axi_if_converter.vhd" :line 107)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arcache : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arprot" :file "../files/common/axi_if_converter.vhd" :line 108)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arqos" :file "../files/common/axi_if_converter.vhd" :line 109)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arqos   : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_aruser" :file "../files/common/axi_if_converter.vhd" :line 110)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_aruser  : out std_logic_vector(C_M_AXI_ARUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arvalid" :file "../files/common/axi_if_converter.vhd" :line 111)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_arready" :file "../files/common/axi_if_converter.vhd" :line 112)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_arready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rid" :file "../files/common/axi_if_converter.vhd" :line 113)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rid     : in  std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rdata" :file "../files/common/axi_if_converter.vhd" :line 114)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rdata   : in  std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rresp" :file "../files/common/axi_if_converter.vhd" :line 115)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rlast" :file "../files/common/axi_if_converter.vhd" :line 116)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rlast   : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_ruser" :file "../files/common/axi_if_converter.vhd" :line 117)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_ruser   : in  std_logic_vector(C_M_AXI_RUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rvalid" :file "../files/common/axi_if_converter.vhd" :line 118)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_lch_rready" :file "../files/common/axi_if_converter.vhd" :line 119)
	       (:type "signal_interface_declaration" :desc "        m_axi_lch_rready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_aclk" :file "../files/common/axi_if_converter.vhd" :line 121)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_aresetn" :file "../files/common/axi_if_converter.vhd" :line 122)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awid" :file "../files/common/axi_if_converter.vhd" :line 123)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awid    : out std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awaddr" :file "../files/common/axi_if_converter.vhd" :line 124)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awaddr  : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awlen" :file "../files/common/axi_if_converter.vhd" :line 125)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awlen   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awsize" :file "../files/common/axi_if_converter.vhd" :line 126)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awsize  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awburst" :file "../files/common/axi_if_converter.vhd" :line 127)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awburst : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awlock" :file "../files/common/axi_if_converter.vhd" :line 128)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awlock  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awcache" :file "../files/common/axi_if_converter.vhd" :line 129)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awcache : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awprot" :file "../files/common/axi_if_converter.vhd" :line 130)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awqos" :file "../files/common/axi_if_converter.vhd" :line 131)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awqos   : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awuser" :file "../files/common/axi_if_converter.vhd" :line 132)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awuser  : out std_logic_vector(C_M_AXI_AWUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awvalid" :file "../files/common/axi_if_converter.vhd" :line 133)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_awready" :file "../files/common/axi_if_converter.vhd" :line 134)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_awready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wdata" :file "../files/common/axi_if_converter.vhd" :line 135)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wdata   : out std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wstrb" :file "../files/common/axi_if_converter.vhd" :line 136)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wstrb   : out std_logic_vector(C_M_AXI_DATA_WIDTH/8-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wlast" :file "../files/common/axi_if_converter.vhd" :line 137)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wlast   : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wuser" :file "../files/common/axi_if_converter.vhd" :line 138)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wuser   : out std_logic_vector(C_M_AXI_WUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wvalid" :file "../files/common/axi_if_converter.vhd" :line 139)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_wready" :file "../files/common/axi_if_converter.vhd" :line 140)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_wready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_bid" :file "../files/common/axi_if_converter.vhd" :line 141)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_bid     : in  std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_bresp" :file "../files/common/axi_if_converter.vhd" :line 142)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_bresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_buser" :file "../files/common/axi_if_converter.vhd" :line 143)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_buser   : in  std_logic_vector(C_M_AXI_BUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_bvalid" :file "../files/common/axi_if_converter.vhd" :line 144)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_bvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_bready" :file "../files/common/axi_if_converter.vhd" :line 145)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_bready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arid" :file "../files/common/axi_if_converter.vhd" :line 146)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arid    : out std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_araddr" :file "../files/common/axi_if_converter.vhd" :line 147)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_araddr  : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arlen" :file "../files/common/axi_if_converter.vhd" :line 148)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arlen   : out std_logic_vector(7 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arsize" :file "../files/common/axi_if_converter.vhd" :line 149)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arsize  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arburst" :file "../files/common/axi_if_converter.vhd" :line 150)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arburst : out std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arlock" :file "../files/common/axi_if_converter.vhd" :line 151)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arlock  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arcache" :file "../files/common/axi_if_converter.vhd" :line 152)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arcache : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arprot" :file "../files/common/axi_if_converter.vhd" :line 153)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arqos" :file "../files/common/axi_if_converter.vhd" :line 154)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arqos   : out std_logic_vector(3 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_aruser" :file "../files/common/axi_if_converter.vhd" :line 155)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_aruser  : out std_logic_vector(C_M_AXI_ARUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arvalid" :file "../files/common/axi_if_converter.vhd" :line 156)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_arready" :file "../files/common/axi_if_converter.vhd" :line 157)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_arready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rid" :file "../files/common/axi_if_converter.vhd" :line 158)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rid     : in  std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rdata" :file "../files/common/axi_if_converter.vhd" :line 159)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rdata   : in  std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rresp" :file "../files/common/axi_if_converter.vhd" :line 160)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rlast" :file "../files/common/axi_if_converter.vhd" :line 161)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rlast   : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_ruser" :file "../files/common/axi_if_converter.vhd" :line 162)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_ruser   : in  std_logic_vector(C_M_AXI_RUSER_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rvalid" :file "../files/common/axi_if_converter.vhd" :line 163)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_rch_rready" :file "../files/common/axi_if_converter.vhd" :line 164)
	       (:type "signal_interface_declaration" :desc "        m_axi_rch_rready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_aclk" :file "../files/common/axi_if_converter.vhd" :line 167)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_aclk    : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_aresetn" :file "../files/common/axi_if_converter.vhd" :line 168)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_aresetn : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_awaddr" :file "../files/common/axi_if_converter.vhd" :line 169)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_awaddr  : out std_logic_vector(C_M_MEM_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_awprot" :file "../files/common/axi_if_converter.vhd" :line 170)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_awprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_awvalid" :file "../files/common/axi_if_converter.vhd" :line 171)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_awvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_awready" :file "../files/common/axi_if_converter.vhd" :line 172)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_awready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_wdata" :file "../files/common/axi_if_converter.vhd" :line 173)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_wdata   : out std_logic_vector(C_M_MEM_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_wstrb" :file "../files/common/axi_if_converter.vhd" :line 174)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_wstrb   : out std_logic_vector(C_M_MEM_AXI_DATA_WIDTH/8-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_wvalid" :file "../files/common/axi_if_converter.vhd" :line 175)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_wvalid  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_wready" :file "../files/common/axi_if_converter.vhd" :line 176)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_wready  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_bresp" :file "../files/common/axi_if_converter.vhd" :line 177)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_bresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_bvalid" :file "../files/common/axi_if_converter.vhd" :line 178)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_bvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_bready" :file "../files/common/axi_if_converter.vhd" :line 179)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_bready  : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_araddr" :file "../files/common/axi_if_converter.vhd" :line 180)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_araddr  : out std_logic_vector(C_M_MEM_AXI_ADDR_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_arprot" :file "../files/common/axi_if_converter.vhd" :line 181)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_arprot  : out std_logic_vector(2 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_arvalid" :file "../files/common/axi_if_converter.vhd" :line 182)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_arvalid : out std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_arready" :file "../files/common/axi_if_converter.vhd" :line 183)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_arready : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_rdata" :file "../files/common/axi_if_converter.vhd" :line 184)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_rdata   : in  std_logic_vector(C_M_MEM_AXI_DATA_WIDTH-1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_rresp" :file "../files/common/axi_if_converter.vhd" :line 185)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_rresp   : in  std_logic_vector(1 downto 0);" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_rvalid" :file "../files/common/axi_if_converter.vhd" :line 186)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_rvalid  : in  std_logic;" :col 8 :parent "axi_if_converter")
	       ("m_axi_conf_rready" :file "../files/common/axi_if_converter.vhd" :line 187)
	       (:type "signal_interface_declaration" :desc "        m_axi_conf_rready  : out std_logic" :col 8 :parent "axi_if_converter")
	       ("axi_if_converter" :file "../files/common/axi_if_converter.vhd" :line 8)
	       (:type "entity_declaration" :desc "entity axi_if_converter is" :col 0 :parent nil)
	       ("soft_reset" :file "../files/common/axi_if_converter.vhd" :line 196)
	       (:type "signal_declaration" :desc "    signal soft_reset : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_aclk" :file "../files/common/axi_if_converter.vhd" :line 199)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_aclk    : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_aresetn" :file "../files/common/axi_if_converter.vhd" :line 200)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_aresetn : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_tdata" :file "../files/common/axi_if_converter.vhd" :line 201)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_tdata   : std_logic_vector(63 downto 0);" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_tvalid" :file "../files/common/axi_if_converter.vhd" :line 202)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_tvalid  : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_tkeep" :file "../files/common/axi_if_converter.vhd" :line 203)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_tlast" :file "../files/common/axi_if_converter.vhd" :line 204)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_tlast   : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_lch_inbuf_tready" :file "../files/common/axi_if_converter.vhd" :line 205)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_inbuf_tready  : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_aclk" :file "../files/common/axi_if_converter.vhd" :line 207)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_aclk    : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_aresetn" :file "../files/common/axi_if_converter.vhd" :line 208)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_aresetn : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_tdata" :file "../files/common/axi_if_converter.vhd" :line 209)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_tdata   : std_logic_vector(63 downto 0);" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_tvalid" :file "../files/common/axi_if_converter.vhd" :line 210)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_tvalid  : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_tkeep" :file "../files/common/axi_if_converter.vhd" :line 211)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_tlast" :file "../files/common/axi_if_converter.vhd" :line 212)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_tlast   : std_logic;" :col 4 :parent "RTL")
	       ("m_axis_rch_inbuf_tready" :file "../files/common/axi_if_converter.vhd" :line 213)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_inbuf_tready  : std_logic;" :col 4 :parent "RTL")
	       ("fb_wr_burst_start_lch" :file "../files/common/axi_if_converter.vhd" :line 216)
	       (:type "signal_declaration" :desc "    signal fb_wr_burst_start_lch : std_logic;" :col 4 :parent "RTL")
	       ("fb_bw_counter_lch" :file "../files/common/axi_if_converter.vhd" :line 217)
	       (:type "signal_declaration" :desc "    signal fb_bw_counter_lch     : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("fb_wlast_lch" :file "../files/common/axi_if_converter.vhd" :line 218)
	       (:type "signal_declaration" :desc "    signal fb_wlast_lch          : std_logic;" :col 4 :parent "RTL")
	       ("fb_reduced_burst_lch" :file "../files/common/axi_if_converter.vhd" :line 219)
	       (:type "signal_declaration" :desc "    signal fb_reduced_burst_lch  : std_logic;" :col 4 :parent "RTL")
	       ("fb_awlen_lch" :file "../files/common/axi_if_converter.vhd" :line 220)
	       (:type "signal_declaration" :desc "    signal fb_awlen_lch          : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("fb_burst_done_lch" :file "../files/common/axi_if_converter.vhd" :line 221)
	       (:type "signal_declaration" :desc "    signal fb_burst_done_lch     : std_logic;" :col 4 :parent "RTL")
	       ("fb_send_size_l" :file "../files/common/axi_if_converter.vhd" :line 222)
	       (:type "signal_declaration" :desc "    signal fb_send_size_l        : unsigned(9 downto 0);" :col 4 :parent "RTL")
	       ("fb_wr_burst_start_rch" :file "../files/common/axi_if_converter.vhd" :line 224)
	       (:type "signal_declaration" :desc "    signal fb_wr_burst_start_rch : std_logic;" :col 4 :parent "RTL")
	       ("fb_bw_counter_rch" :file "../files/common/axi_if_converter.vhd" :line 225)
	       (:type "signal_declaration" :desc "    signal fb_bw_counter_rch     : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("fb_wlast_rch" :file "../files/common/axi_if_converter.vhd" :line 226)
	       (:type "signal_declaration" :desc "    signal fb_wlast_rch          : std_logic;" :col 4 :parent "RTL")
	       ("fb_reduced_burst_rch" :file "../files/common/axi_if_converter.vhd" :line 227)
	       (:type "signal_declaration" :desc "    signal fb_reduced_burst_rch  : std_logic;" :col 4 :parent "RTL")
	       ("fb_awlen_rch" :file "../files/common/axi_if_converter.vhd" :line 228)
	       (:type "signal_declaration" :desc "    signal fb_awlen_rch          : std_logic_vector(7 downto 0);" :col 4 :parent "RTL")
	       ("fb_burst_done_rch" :file "../files/common/axi_if_converter.vhd" :line 229)
	       (:type "signal_declaration" :desc "    signal fb_burst_done_rch     : std_logic;" :col 4 :parent "RTL")
	       ("fb_send_size_r" :file "../files/common/axi_if_converter.vhd" :line 230)
	       (:type "signal_declaration" :desc "    signal fb_send_size_r        : unsigned(9 downto 0);" :col 4 :parent "RTL")
	       ("bram_overflow_error" :file "../files/common/axi_if_converter.vhd" :line 233)
	       (:type "signal_declaration" :desc "    signal bram_overflow_error       : std_logic;" :col 4 :parent "RTL")
	       ("out_reg_underflow_error_l" :file "../files/common/axi_if_converter.vhd" :line 234)
	       (:type "signal_declaration" :desc "    signal out_reg_underflow_error_l : std_logic;" :col 4 :parent "RTL")
	       ("out_reg_overflow_error_l" :file "../files/common/axi_if_converter.vhd" :line 235)
	       (:type "signal_declaration" :desc "    signal out_reg_overflow_error_l  : std_logic;" :col 4 :parent "RTL")
	       ("out_reg_underflow_error_r" :file "../files/common/axi_if_converter.vhd" :line 236)
	       (:type "signal_declaration" :desc "    signal out_reg_underflow_error_r : std_logic;" :col 4 :parent "RTL")
	       ("out_reg_overflow_error_r" :file "../files/common/axi_if_converter.vhd" :line 237)
	       (:type "signal_declaration" :desc "    signal out_reg_overflow_error_r  : std_logic;" :col 4 :parent "RTL")
	       ("transaction_error" :file "../files/common/axi_if_converter.vhd" :line 240)
	       (:type "signal_declaration" :desc "    signal transaction_error : std_logic;" :col 4 :parent "RTL")
	       ("write_request" :file "../files/common/axi_if_converter.vhd" :line 242)
	       (:type "signal_declaration" :desc "    signal write_request : std_logic;" :col 4 :parent "RTL")
	       ("write_data" :file "../files/common/axi_if_converter.vhd" :line 243)
	       (:type "signal_declaration" :desc "    signal write_data    : std_logic_vector(31 downto 0);" :col 4 :parent "RTL")
	       ("write_address" :file "../files/common/axi_if_converter.vhd" :line 244)
	       (:type "signal_declaration" :desc "    signal write_address : std_logic_vector(31 downto 0);" :col 4 :parent "RTL")
	       ("write_done" :file "../files/common/axi_if_converter.vhd" :line 245)
	       (:type "signal_declaration" :desc "    signal write_done    : std_logic;" :col 4 :parent "RTL")
	       ("read_request" :file "../files/common/axi_if_converter.vhd" :line 247)
	       (:type "signal_declaration" :desc "    signal read_request    : std_logic;" :col 4 :parent "RTL")
	       ("read_address" :file "../files/common/axi_if_converter.vhd" :line 248)
	       (:type "signal_declaration" :desc "    signal read_address    : std_logic_vector(31 downto 0);" :col 4 :parent "RTL")
	       ("read_data" :file "../files/common/axi_if_converter.vhd" :line 249)
	       (:type "signal_declaration" :desc "    signal read_data       : std_logic_vector (31 downto 0);" :col 4 :parent "RTL")
	       ("read_data_valid" :file "../files/common/axi_if_converter.vhd" :line 250)
	       (:type "signal_declaration" :desc "    signal read_data_valid : std_logic;" :col 4 :parent "RTL")
	       ("count_lch" :file "../files/common/axi_if_converter.vhd" :line 253)
	       (:type "signal_declaration" :desc "    signal count_lch         : unsigned(31 downto 0);" :col 4 :parent "RTL")
	       ("pattern_count_lch" :file "../files/common/axi_if_converter.vhd" :line 254)
	       (:type "signal_declaration" :desc "    signal pattern_count_lch : unsigned(31 downto 0);" :col 4 :parent "RTL")
	       ("count_rch" :file "../files/common/axi_if_converter.vhd" :line 255)
	       (:type "signal_declaration" :desc "    signal count_rch         : unsigned(31 downto 0);" :col 4 :parent "RTL")
	       ("pattern_count_rch" :file "../files/common/axi_if_converter.vhd" :line 256)
	       (:type "signal_declaration" :desc "    signal pattern_count_rch : unsigned(31 downto 0);" :col 4 :parent "RTL")
	       ("system_enable" :file "../files/common/axi_if_converter.vhd" :line 259)
	       (:type "signal_declaration" :desc "    signal system_enable      : std_logic;" :col 4 :parent "RTL")
	       ("system_running" :file "../files/common/axi_if_converter.vhd" :line 260)
	       (:type "signal_declaration" :desc "    signal system_running     : std_logic;" :col 4 :parent "RTL")
	       ("system_running_lch" :file "../files/common/axi_if_converter.vhd" :line 261)
	       (:type "signal_declaration" :desc "    signal system_running_lch : std_logic;" :col 4 :parent "RTL")
	       ("system_running_rch" :file "../files/common/axi_if_converter.vhd" :line 262)
	       (:type "signal_declaration" :desc "    signal system_running_rch : std_logic;" :col 4 :parent "RTL")
	       ("conv_op_lch" :file "../files/common/axi_if_converter.vhd" :line 263)
	       (:type "signal_declaration" :desc "    signal conv_op_lch        : std_logic;" :col 4 :parent "RTL")
	       ("conv_op_rch" :file "../files/common/axi_if_converter.vhd" :line 264)
	       (:type "signal_declaration" :desc "    signal conv_op_rch        : std_logic;" :col 4 :parent "RTL")
	       ("read_size_l" :file "../files/common/axi_if_converter.vhd" :line 265)
	       (:type "signal_declaration" :desc "    signal read_size_l        : unsigned(15 downto 0);" :col 4 :parent "RTL")
	       ("read_size_r" :file "../files/common/axi_if_converter.vhd" :line 266)
	       (:type "signal_declaration" :desc "    signal read_size_r        : unsigned(15 downto 0);" :col 4 :parent "RTL")
	       ("conv_req_lch" :file "../files/common/axi_if_converter.vhd" :line 270)
	       (:type "signal_declaration" :desc "    signal conv_req_lch         : conversion_req_t;" :col 4 :parent "RTL")
	       ("conv_rsp_lch" :file "../files/common/axi_if_converter.vhd" :line 271)
	       (:type "signal_declaration" :desc "    signal conv_rsp_lch         : conversion_rsp_t;" :col 4 :parent "RTL")
	       ("internal_error_lch" :file "../files/common/axi_if_converter.vhd" :line 272)
	       (:type "signal_declaration" :desc "    signal internal_error_lch   : std_logic;" :col 4 :parent "RTL")
	       ("pattern_req_lch" :file "../files/common/axi_if_converter.vhd" :line 273)
	       (:type "signal_declaration" :desc "    signal pattern_req_lch      : std_logic;" :col 4 :parent "RTL")
	       ("pattern_len_lch" :file "../files/common/axi_if_converter.vhd" :line 274)
	       (:type "signal_declaration" :desc "    signal pattern_len_lch      : unsigned(9 downto 0);" :col 4 :parent "RTL")
	       ("pattern_finished_lch" :file "../files/common/axi_if_converter.vhd" :line 275)
	       (:type "signal_declaration" :desc "    signal pattern_finished_lch : std_logic;" :col 4 :parent "RTL")
	       ("pattern_tlast_lch" :file "../files/common/axi_if_converter.vhd" :line 276)
	       (:type "signal_declaration" :desc "    signal pattern_tlast_lch    : std_logic;" :col 4 :parent "RTL")
	       ("conv_req_rch" :file "../files/common/axi_if_converter.vhd" :line 278)
	       (:type "signal_declaration" :desc "    signal conv_req_rch         : conversion_req_t;" :col 4 :parent "RTL")
	       ("conv_rsp_rch" :file "../files/common/axi_if_converter.vhd" :line 279)
	       (:type "signal_declaration" :desc "    signal conv_rsp_rch         : conversion_rsp_t;" :col 4 :parent "RTL")
	       ("internal_error_rch" :file "../files/common/axi_if_converter.vhd" :line 280)
	       (:type "signal_declaration" :desc "    signal internal_error_rch   : std_logic;" :col 4 :parent "RTL")
	       ("pattern_req_rch" :file "../files/common/axi_if_converter.vhd" :line 281)
	       (:type "signal_declaration" :desc "    signal pattern_req_rch      : std_logic;" :col 4 :parent "RTL")
	       ("pattern_len_rch" :file "../files/common/axi_if_converter.vhd" :line 282)
	       (:type "signal_declaration" :desc "    signal pattern_len_rch      : unsigned(9 downto 0);" :col 4 :parent "RTL")
	       ("pattern_finished_rch" :file "../files/common/axi_if_converter.vhd" :line 283)
	       (:type "signal_declaration" :desc "    signal pattern_finished_rch : std_logic;" :col 4 :parent "RTL")
	       ("pattern_tlast_rch" :file "../files/common/axi_if_converter.vhd" :line 284)
	       (:type "signal_declaration" :desc "    signal pattern_tlast_rch    : std_logic;" :col 4 :parent "RTL")
	       ("buffer_size_l" :file "../files/common/axi_if_converter.vhd" :line 287)
	       (:type "signal_declaration" :desc "    signal buffer_size_l : unsigned(10 downto 0);" :col 4 :parent "RTL")
	       ("bram_ptr_l" :file "../files/common/axi_if_converter.vhd" :line 288)
	       (:type "signal_declaration" :desc "    signal bram_ptr_l    : std_logic_vector(31 downto 0);" :col 4 :parent "RTL")
	       ("buffer_size_r" :file "../files/common/axi_if_converter.vhd" :line 289)
	       (:type "signal_declaration" :desc "    signal buffer_size_r : unsigned(10 downto 0);" :col 4 :parent "RTL")
	       ("bram_ptr_r" :file "../files/common/axi_if_converter.vhd" :line 290)
	       (:type "signal_declaration" :desc "    signal bram_ptr_r    : std_logic_vector(31 downto 0);" :col 4 :parent "RTL")
	       ("clk_fs" :file "../files/common/axi_if_converter.vhd" :line 293)
	       (:type "signal_declaration" :desc "    signal clk_fs      : std_logic;" :col 4 :parent "RTL")
	       ("clk_fs_sync" :file "../files/common/axi_if_converter.vhd" :line 294)
	       (:type "signal_declaration" :desc "    signal clk_fs_sync : std_logic;" :col 4 :parent "RTL")
	       ("RTL" :file "../files/common/axi_if_converter.vhd" :line 193)
	       (:type "architecture_body" :desc "architecture RTL of axi_if_converter is" :col 0 :parent nil)))
