#s(hash-table test equal data
	      (("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 12)
	       (:type "constant_declaration" :desc "    constant AXI_CLK_T : time := 6.4 ns;" :col 4 :parent "global_sim")
	       ("FS_CLK_T" :file "../files/common/global_sim.vhd" :line 13)
	       (:type "constant_declaration" :desc "    constant FS_CLK_T  : time := 22675 ns;  -- 44,1 Khz" :col 4 :parent "global_sim")
	       ("CONTROL_REG_ADDR" :file "../files/common/global_sim.vhd" :line 16)
	       (:type "constant_declaration" :desc "    constant CONTROL_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0000\";" :col 4 :parent "global_sim")
	       ("STATUS_REG_ADDR" :file "../files/common/global_sim.vhd" :line 17)
	       (:type "constant_declaration" :desc "    constant STATUS_REG_ADDR               : std_logic_vector(31 downto 0) := x\"0000_0004\";" :col 4 :parent "global_sim")
	       ("VERSION_REG_ADDR" :file "../files/common/global_sim.vhd" :line 18)
	       (:type "constant_declaration" :desc "    constant VERSION_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0008\";" :col 4 :parent "global_sim")
	       ("CONVERTER_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 19)
	       (:type "constant_declaration" :desc "    constant CONVERTER_SETUP_REG_ADDR      : std_logic_vector(31 downto 0) := x\"0000_000C\";" :col 4 :parent "global_sim")
	       ("MM2S_SIZE_REG_ADDR" :file "../files/common/global_sim.vhd" :line 20)
	       (:type "constant_declaration" :desc "    constant MM2S_SIZE_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0010\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_WR_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 21)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_WR_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0014\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_WR_ADDR_REG_ADDR" :file "../files/common/global_sim.vhd" :line 22)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_WR_ADDR_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0018\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_WR_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 23)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_WR_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_001C\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_RD_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 24)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_RD_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0020\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_RD_ADD_REG_ADDR" :file "../files/common/global_sim.vhd" :line 25)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_RD_ADD_REG_ADDR   : std_logic_vector(31 downto 0) := x\"0000_0024\";" :col 4 :parent "global_sim")
	       ("MASTER_LITE_RD_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 26)
	       (:type "constant_declaration" :desc "    constant MASTER_LITE_RD_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0028\";" :col 4 :parent "global_sim")
	       ("COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 27)
	       (:type "constant_declaration" :desc "    constant COUNT_LCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_002C\";" :col 4 :parent "global_sim")
	       ("PATTERN_COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 28)
	       (:type "constant_declaration" :desc "    constant PATTERN_COUNT_LCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0030\";" :col 4 :parent "global_sim")
	       ("COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 29)
	       (:type "constant_declaration" :desc "    constant COUNT_RCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0034\";" :col 4 :parent "global_sim")
	       ("PATTERN_COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 30)
	       (:type "constant_declaration" :desc "    constant PATTERN_COUNT_RCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0038\";" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 36)
	       (:type "signal_interface_declaration" :desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 32 :parent "read_control_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 36)
	       (:type "signal_interface_declaration" :desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 88 :parent "read_control_reg")
	       ("read_control_reg" :file "../files/common/global_sim.vhd" :line 36)
	       (:type "procedure_declaration" :desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 37)
	       (:type "signal_interface_declaration" :desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 31 :parent "read_status_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 37)
	       (:type "signal_interface_declaration" :desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 88 :parent "read_status_reg")
	       ("read_status_reg" :file "../files/common/global_sim.vhd" :line 37)
	       (:type "procedure_declaration" :desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 38)
	       (:type "signal_interface_declaration" :desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 32 :parent "read_version_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 38)
	       (:type "signal_interface_declaration" :desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 88 :parent "read_version_reg")
	       ("read_version_reg" :file "../files/common/global_sim.vhd" :line 38)
	       (:type "procedure_declaration" :desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 39)
	       (:type "signal_interface_declaration" :desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 29 :parent "read_counters")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 39)
	       (:type "signal_interface_declaration" :desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 88 :parent "read_counters")
	       ("read_counters" :file "../files/common/global_sim.vhd" :line 39)
	       (:type "procedure_declaration" :desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 40)
	       (:type "signal_interface_declaration" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 43 :parent "read_master_lite_rd_data_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 40)
	       (:type "signal_interface_declaration" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 88 :parent "read_master_lite_rd_data_reg")
	       ("read_master_lite_rd_data_reg" :file "../files/common/global_sim.vhd" :line 40)
	       (:type "procedure_declaration" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 43)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 32 :parent "write_control_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 43)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_control_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 43)
	       (:type "constant_interface_declaration" :desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_control_reg")
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 43)
	       (:type "procedure_declaration" :desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 44)
	       (:type "signal_interface_declaration" :desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 40 :parent "write_converter_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 44)
	       (:type "signal_interface_declaration" :desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_converter_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 44)
	       (:type "constant_interface_declaration" :desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_converter_setup_reg")
	       ("write_converter_setup_reg" :file "../files/common/global_sim.vhd" :line 44)
	       (:type "procedure_declaration" :desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 45)
	       (:type "signal_interface_declaration" :desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 34 :parent "write_mm2s_size_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 45)
	       (:type "signal_interface_declaration" :desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_mm2s_size_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 45)
	       (:type "constant_interface_declaration" :desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_mm2s_size_reg")
	       ("write_mm2s_size_reg" :file "../files/common/global_sim.vhd" :line 45)
	       (:type "procedure_declaration" :desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 46)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 45 :parent "write_master_lite_wr_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 46)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_master_lite_wr_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 46)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_master_lite_wr_setup_reg")
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 46)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 47)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 43 :parent "write_master_lite_wr_add_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 47)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_master_lite_wr_add_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 47)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_master_lite_wr_add_reg")
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 47)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 48)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 44 :parent "write_master_lite_wr_data_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 48)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_master_lite_wr_data_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 48)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_master_lite_wr_data_reg")
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 48)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 49)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 45 :parent "write_master_lite_rd_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 49)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_master_lite_rd_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 49)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_master_lite_rd_setup_reg")
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 49)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 50)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 43 :parent "write_master_lite_rd_add_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 50)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 90 :parent "write_master_lite_rd_add_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 50)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 138 :parent "write_master_lite_rd_add_reg")
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 50)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 53)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 47 :parent "write_control_reg_system_enable")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 53)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 92 :parent "write_control_reg_system_enable")
	       ("write_control_reg_system_enable" :file "../files/common/global_sim.vhd" :line 53)
	       (:type "procedure_declaration" :desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 54)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 45 :parent "write_control_reg_system_stop")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 54)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 92 :parent "write_control_reg_system_stop")
	       ("write_control_reg_system_stop" :file "../files/common/global_sim.vhd" :line 54)
	       (:type "procedure_declaration" :desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 55)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 44 :parent "write_control_reg_soft_reset")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 55)
	       (:type "signal_interface_declaration" :desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 92 :parent "write_control_reg_soft_reset")
	       ("write_control_reg_soft_reset" :file "../files/common/global_sim.vhd" :line 55)
	       (:type "procedure_declaration" :desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 56)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 47 :parent "write_master_lite_write_request")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 56)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 92 :parent "write_master_lite_write_request")
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 56)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 140 :parent "write_master_lite_write_request")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 56)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 190 :parent "write_master_lite_write_request")
	       ("write_master_lite_write_request" :file "../files/common/global_sim.vhd" :line 56)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 57)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 46 :parent "write_master_lite_read_request")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 57)
	       (:type "signal_interface_declaration" :desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 92 :parent "write_master_lite_read_request")
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 57)
	       (:type "constant_interface_declaration" :desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 140 :parent "write_master_lite_read_request")
	       ("write_master_lite_read_request" :file "../files/common/global_sim.vhd" :line 57)
	       (:type "procedure_declaration" :desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 4 :parent "global_sim")
	       ("stop_clock" :file "../files/common/global_sim.vhd" :line 60)
	       (:type "signal_interface_declaration" :desc "    procedure end_test_and_stop_clock(signal stop_clock : out std_logic);" :col 38 :parent "end_test_and_stop_clock")
	       ("end_test_and_stop_clock" :file "../files/common/global_sim.vhd" :line 60)
	       (:type "procedure_declaration" :desc "    procedure end_test_and_stop_clock(signal stop_clock : out std_logic);" :col 4 :parent "global_sim")
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 9)
	       (:type "package_declaration" :desc "package global_sim is" :col 0 :parent nil)
	       ("stop_clock" :file "../files/common/global_sim.vhd" :line 69)
	       (:type "signal_interface_declaration" :desc "    procedure end_test_and_stop_clock (signal stop_clock : out std_logic) is" :col 39 :parent "end_test_and_stop_clock")
	       ("end_test_and_stop_clock" :file "../files/common/global_sim.vhd" :line 69)
	       (:type "procedure_body" :desc "    procedure end_test_and_stop_clock (signal stop_clock : out std_logic) is" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 78)
	       (:type "signal_interface_declaration" :desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 32 :parent "read_control_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 78)
	       (:type "signal_interface_declaration" :desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 77 :parent "read_control_reg")
	       ("read_control_reg" :file "../files/common/global_sim.vhd" :line 78)
	       (:type "procedure_body" :desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 85)
	       (:type "signal_interface_declaration" :desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 31 :parent "read_status_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 85)
	       (:type "signal_interface_declaration" :desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 76 :parent "read_status_reg")
	       ("read_status_reg" :file "../files/common/global_sim.vhd" :line 85)
	       (:type "procedure_body" :desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 92)
	       (:type "signal_interface_declaration" :desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 32 :parent "read_version_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 92)
	       (:type "signal_interface_declaration" :desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 77 :parent "read_version_reg")
	       ("read_version_reg" :file "../files/common/global_sim.vhd" :line 92)
	       (:type "procedure_body" :desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 99)
	       (:type "signal_interface_declaration" :desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 29 :parent "read_counters")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 99)
	       (:type "signal_interface_declaration" :desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 74 :parent "read_counters")
	       ("read_counters" :file "../files/common/global_sim.vhd" :line 99)
	       (:type "procedure_body" :desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 4 :parent "global_sim")
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 109)
	       (:type "signal_interface_declaration" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 43 :parent "read_master_lite_rd_data_reg")
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 109)
	       (:type "signal_interface_declaration" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 88 :parent "read_master_lite_rd_data_reg")
	       ("read_master_lite_rd_data_reg" :file "../files/common/global_sim.vhd" :line 109)
	       (:type "procedure_body" :desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 118)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_control_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 119)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_control_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 120)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_control_reg")
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 117)
	       (:type "procedure_body" :desc "    procedure write_control_reg (" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 129)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_converter_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 130)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_converter_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 131)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_converter_setup_reg")
	       ("write_converter_setup_reg" :file "../files/common/global_sim.vhd" :line 128)
	       (:type "procedure_body" :desc "    procedure write_converter_setup_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 140)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_mm2s_size_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 141)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_mm2s_size_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 142)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_mm2s_size_reg")
	       ("write_mm2s_size_reg" :file "../files/common/global_sim.vhd" :line 139)
	       (:type "procedure_body" :desc "    procedure write_mm2s_size_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 151)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_wr_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 152)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_wr_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 153)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_wr_setup_reg")
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 150)
	       (:type "procedure_body" :desc "    procedure write_master_lite_wr_setup_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 162)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_wr_add_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 163)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_wr_add_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 164)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_wr_add_reg")
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 161)
	       (:type "procedure_body" :desc "    procedure write_master_lite_wr_add_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 173)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_wr_data_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 174)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_wr_data_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 175)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_wr_data_reg")
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 172)
	       (:type "procedure_body" :desc "    procedure write_master_lite_wr_data_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 184)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_rd_setup_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 185)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_rd_setup_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 186)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_rd_setup_reg")
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 183)
	       (:type "procedure_body" :desc "    procedure write_master_lite_rd_setup_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 195)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_rd_add_reg")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 196)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_rd_add_reg")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 197)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_rd_add_reg")
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 194)
	       (:type "procedure_body" :desc "    procedure write_master_lite_rd_add_reg(" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 207)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_control_reg_system_enable")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 208)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out" :col 8 :parent "write_control_reg_system_enable")
	       ("write_control_reg_system_enable" :file "../files/common/global_sim.vhd" :line 206)
	       (:type "procedure_body" :desc "    procedure write_control_reg_system_enable (" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 217)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_control_reg_system_stop")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 218)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out" :col 8 :parent "write_control_reg_system_stop")
	       ("write_control_reg_system_stop" :file "../files/common/global_sim.vhd" :line 216)
	       (:type "procedure_body" :desc "    procedure write_control_reg_system_stop (" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 227)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_control_reg_soft_reset")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 228)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out" :col 8 :parent "write_control_reg_soft_reset")
	       ("write_control_reg_soft_reset" :file "../files/common/global_sim.vhd" :line 226)
	       (:type "procedure_body" :desc "    procedure write_control_reg_soft_reset (" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 237)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_write_request")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 238)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_write_request")
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 239)
	       (:type "constant_interface_declaration" :desc "        constant ADDR    : in  std_logic_vector(31 downto 0);" :col 8 :parent "write_master_lite_write_request")
	       ("DATA" :file "../files/common/global_sim.vhd" :line 240)
	       (:type "constant_interface_declaration" :desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_write_request")
	       ("write_master_lite_write_request" :file "../files/common/global_sim.vhd" :line 236)
	       (:type "procedure_body" :desc "    procedure write_master_lite_write_request (" :col 4 :parent "global_sim")
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 251)
	       (:type "signal_interface_declaration" :desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 8 :parent "write_master_lite_read_request")
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 252)
	       (:type "signal_interface_declaration" :desc "        signal bfm_out_w : out s_common_response_w_out;" :col 8 :parent "write_master_lite_read_request")
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 253)
	       (:type "constant_interface_declaration" :desc "        constant ADDR    : in  std_logic_vector(31 downto 0)" :col 8 :parent "write_master_lite_read_request")
	       ("write_master_lite_read_request" :file "../files/common/global_sim.vhd" :line 250)
	       (:type "procedure_body" :desc "    procedure write_master_lite_read_request (" :col 4 :parent "global_sim")
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 66)
	       (:type "package_body" :desc "package body global_sim is" :col 0 :parent nil)))
