#s(hash-table test equal data
	      (("conversion_op" :file "../files/common/global_pkg.vhd" :line 11)
	       (:type "full_type_declaration" :desc "    type conversion_op is (S2MM, MM2S);" :col 4 :parent "global")
	       ("op_type" :file "../files/common/global_pkg.vhd" :line 14)
	       (:type "element_declaration" :desc "        op_type : conversion_op;" :col 8 :parent "conversion_req_t")
	       ("request" :file "../files/common/global_pkg.vhd" :line 15)
	       (:type "element_declaration" :desc "        request : std_logic;" :col 8 :parent "conversion_req_t")
	       ("size" :file "../files/common/global_pkg.vhd" :line 16)
	       (:type "element_declaration" :desc "        size    : unsigned(9 downto 0);" :col 8 :parent "conversion_req_t")
	       ("address" :file "../files/common/global_pkg.vhd" :line 17)
	       (:type "element_declaration" :desc "        address : std_logic_vector(31 downto 0);" :col 8 :parent "conversion_req_t")
	       ("conversion_req_t" :file "../files/common/global_pkg.vhd" :line 13)
	       (:type "full_type_declaration" :desc "    type conversion_req_t is record" :col 4 :parent "global")
	       ("s2mm_done" :file "../files/common/global_pkg.vhd" :line 21)
	       (:type "element_declaration" :desc "        s2mm_done : std_logic;" :col 8 :parent "conversion_rsp_t")
	       ("mm2s_done" :file "../files/common/global_pkg.vhd" :line 22)
	       (:type "element_declaration" :desc "        mm2s_done : std_logic;" :col 8 :parent "conversion_rsp_t")
	       ("conversion_rsp_t" :file "../files/common/global_pkg.vhd" :line 20)
	       (:type "full_type_declaration" :desc "    type conversion_rsp_t is record" :col 4 :parent "global")
	       ("C_S_AXI_DATA_WIDTH" :file "../files/common/global_pkg.vhd" :line 29)
	       (:type "constant_declaration" :desc "    constant C_S_AXI_DATA_WIDTH : integer := 32;" :col 4 :parent "global")
	       ("C_S_AXI_ADDR_WIDTH" :file "../files/common/global_pkg.vhd" :line 30)
	       (:type "constant_declaration" :desc "    constant C_S_AXI_ADDR_WIDTH : integer := 7;" :col 4 :parent "global")
	       ("C_M_AXI_BURST_LEN" :file "../files/common/global_pkg.vhd" :line 33)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_BURST_LEN    : integer := 32;" :col 4 :parent "global")
	       ("C_M_AXI_ID_WIDTH" :file "../files/common/global_pkg.vhd" :line 34)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_ID_WIDTH     : integer := 1;" :col 4 :parent "global")
	       ("C_M_AXI_ADDR_WIDTH" :file "../files/common/global_pkg.vhd" :line 35)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_ADDR_WIDTH   : integer := 32;" :col 4 :parent "global")
	       ("C_M_AXI_DATA_WIDTH" :file "../files/common/global_pkg.vhd" :line 36)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_DATA_WIDTH   : integer := 64;" :col 4 :parent "global")
	       ("C_M_AXI_AWUSER_WIDTH" :file "../files/common/global_pkg.vhd" :line 37)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_AWUSER_WIDTH : integer := 0;" :col 4 :parent "global")
	       ("C_M_AXI_ARUSER_WIDTH" :file "../files/common/global_pkg.vhd" :line 38)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_ARUSER_WIDTH : integer := 0;" :col 4 :parent "global")
	       ("C_M_AXI_WUSER_WIDTH" :file "../files/common/global_pkg.vhd" :line 39)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_WUSER_WIDTH  : integer := 0;" :col 4 :parent "global")
	       ("C_M_AXI_RUSER_WIDTH" :file "../files/common/global_pkg.vhd" :line 40)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_RUSER_WIDTH  : integer := 0;" :col 4 :parent "global")
	       ("C_M_AXI_BUSER_WIDTH" :file "../files/common/global_pkg.vhd" :line 41)
	       (:type "constant_declaration" :desc "    constant C_M_AXI_BUSER_WIDTH  : integer := 0;" :col 4 :parent "global")
	       ("C_M_MEM_AXI_TARGET_SLAVE_BASE_ADDR" :file "../files/common/global_pkg.vhd" :line 44)
	       (:type "constant_declaration" :desc "    constant C_M_MEM_AXI_TARGET_SLAVE_BASE_ADDR : std_logic_vector := x\"0000_0000\";" :col 4 :parent "global")
	       ("C_M_MEM_AXI_ADDR_WIDTH" :file "../files/common/global_pkg.vhd" :line 45)
	       (:type "constant_declaration" :desc "    constant C_M_MEM_AXI_ADDR_WIDTH             : integer          := 32;" :col 4 :parent "global")
	       ("C_M_MEM_AXI_DATA_WIDTH" :file "../files/common/global_pkg.vhd" :line 46)
	       (:type "constant_declaration" :desc "    constant C_M_MEM_AXI_DATA_WIDTH             : integer          := 32;" :col 4 :parent "global")
	       ("PATTERN_COUNTER_DATA_WIDTH" :file "../files/common/global_pkg.vhd" :line 49)
	       (:type "constant_declaration" :desc "    constant PATTERN_COUNTER_DATA_WIDTH : integer := 64;" :col 4 :parent "global")
	       ("PATTERN" :file "../files/common/global_pkg.vhd" :line 50)
	       (:type "constant_declaration" :desc "    constant PATTERN : std_logic_vector(PATTERN_COUNTER_DATA_WIDTH-1 downto 0) := (others => '0');" :col 4 :parent "global")
	       ("DIV_FACTOR" :file "../files/common/global_pkg.vhd" :line 53)
	       (:type "constant_declaration" :desc "    constant DIV_FACTOR : integer := 16;" :col 4 :parent "global")
	       ("LEFT_CH_ST_BASE_ADDRESS" :file "../files/common/global_pkg.vhd" :line 56)
	       (:type "constant_declaration" :desc "    constant LEFT_CH_ST_BASE_ADDRESS  : std_logic_vector(31 downto 0) := x\"1000_0000\";" :col 4 :parent "global")
	       ("RIGHT_CH_ST_BASE_ADDRESS" :file "../files/common/global_pkg.vhd" :line 57)
	       (:type "constant_declaration" :desc "    constant RIGHT_CH_ST_BASE_ADDRESS : std_logic_vector(31 downto 0) := x\"2000_0000\";" :col 4 :parent "global")
	       ("global" :file "../files/common/global_pkg.vhd" :line 5)
	       (:type "package_declaration" :desc "package global is" :col 0 :parent nil)))
