#s(hash-table test equal data
	      (("IEEE" :file "../files/common/global_sim.vhd" :line 1)
	       (:desc "library IEEE;" :col 8)
	       ("IEEE" :file "../files/common/global_sim.vhd" :line 2)
	       (:desc "use IEEE.std_logic_1164.all;" :col 4)
	       ("std_logic_1164" :file "../files/common/global_sim.vhd" :line 2)
	       (:desc "use IEEE.std_logic_1164.all;" :col 9)
	       ("IEEE" :file "../files/common/global_sim.vhd" :line 3)
	       (:desc "use IEEE.numeric_std.all;" :col 4)
	       ("numeric_std" :file "../files/common/global_sim.vhd" :line 3)
	       (:desc "use IEEE.numeric_std.all;" :col 9)
	       ("xil_defaultlib" :file "../files/common/global_sim.vhd" :line 4)
	       (:desc "library xil_defaultlib;" :col 8)
	       ("xil_defaultlib" :file "../files/common/global_sim.vhd" :line 5)
	       (:desc "use xil_defaultlib.global.all;" :col 4)
	       ("global" :file "../files/common/global_sim.vhd" :line 5)
	       (:desc "use xil_defaultlib.global.all;" :col 19)
	       ("xil_defaultlib" :file "../files/common/global_sim.vhd" :line 6)
	       (:desc "use xil_defaultlib.axil_slave_bfm.all;" :col 4)
	       ("axil_slave_bfm" :file "../files/common/global_sim.vhd" :line 6)
	       (:desc "use xil_defaultlib.axil_slave_bfm.all;" :col 19)
	       ("xil_defaultlib" :file "../files/common/global_sim.vhd" :line 7)
	       (:desc "use xil_defaultlib.axil_master_bfm.all;" :col 4)
	       ("axil_master_bfm" :file "../files/common/global_sim.vhd" :line 7)
	       (:desc "use xil_defaultlib.axil_master_bfm.all;" :col 19)
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 9)
	       (:desc "package global_sim is" :col 8)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 12)
	       (:desc "    constant AXI_CLK_T : time := 6.4 ns;" :col 13)
	       ("time" :file "../files/common/global_sim.vhd" :line 12)
	       (:desc "    constant AXI_CLK_T : time := 6.4 ns;" :col 25)
	       ("ns" :file "../files/common/global_sim.vhd" :line 12)
	       (:desc "    constant AXI_CLK_T : time := 6.4 ns;" :col 37)
	       ("FS_CLK_T" :file "../files/common/global_sim.vhd" :line 13)
	       (:desc "    constant FS_CLK_T  : time := 22675 ns;  -- 44,1 Khz" :col 13)
	       ("time" :file "../files/common/global_sim.vhd" :line 13)
	       (:desc "    constant FS_CLK_T  : time := 22675 ns;  -- 44,1 Khz" :col 25)
	       ("ns" :file "../files/common/global_sim.vhd" :line 13)
	       (:desc "    constant FS_CLK_T  : time := 22675 ns;  -- 44,1 Khz" :col 39)
	       ("CONTROL_REG_ADDR" :file "../files/common/global_sim.vhd" :line 16)
	       (:desc "    constant CONTROL_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0000\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 16)
	       (:desc "    constant CONTROL_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0000\";" :col 45)
	       ("STATUS_REG_ADDR" :file "../files/common/global_sim.vhd" :line 17)
	       (:desc "    constant STATUS_REG_ADDR               : std_logic_vector(31 downto 0) := x\"0000_0004\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 17)
	       (:desc "    constant STATUS_REG_ADDR               : std_logic_vector(31 downto 0) := x\"0000_0004\";" :col 45)
	       ("VERSION_REG_ADDR" :file "../files/common/global_sim.vhd" :line 18)
	       (:desc "    constant VERSION_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0008\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 18)
	       (:desc "    constant VERSION_REG_ADDR              : std_logic_vector(31 downto 0) := x\"0000_0008\";" :col 45)
	       ("CONVERTER_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 19)
	       (:desc "    constant CONVERTER_SETUP_REG_ADDR      : std_logic_vector(31 downto 0) := x\"0000_000C\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 19)
	       (:desc "    constant CONVERTER_SETUP_REG_ADDR      : std_logic_vector(31 downto 0) := x\"0000_000C\";" :col 45)
	       ("MM2S_SIZE_REG_ADDR" :file "../files/common/global_sim.vhd" :line 20)
	       (:desc "    constant MM2S_SIZE_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0010\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 20)
	       (:desc "    constant MM2S_SIZE_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0010\";" :col 45)
	       ("MASTER_LITE_WR_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 21)
	       (:desc "    constant MASTER_LITE_WR_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0014\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 21)
	       (:desc "    constant MASTER_LITE_WR_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0014\";" :col 45)
	       ("MASTER_LITE_WR_ADDR_REG_ADDR" :file "../files/common/global_sim.vhd" :line 22)
	       (:desc "    constant MASTER_LITE_WR_ADDR_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0018\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 22)
	       (:desc "    constant MASTER_LITE_WR_ADDR_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0018\";" :col 45)
	       ("MASTER_LITE_WR_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 23)
	       (:desc "    constant MASTER_LITE_WR_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_001C\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 23)
	       (:desc "    constant MASTER_LITE_WR_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_001C\";" :col 45)
	       ("MASTER_LITE_RD_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 24)
	       (:desc "    constant MASTER_LITE_RD_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0020\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 24)
	       (:desc "    constant MASTER_LITE_RD_SETUP_REG_ADDR : std_logic_vector(31 downto 0) := x\"0000_0020\";" :col 45)
	       ("MASTER_LITE_RD_ADD_REG_ADDR" :file "../files/common/global_sim.vhd" :line 25)
	       (:desc "    constant MASTER_LITE_RD_ADD_REG_ADDR   : std_logic_vector(31 downto 0) := x\"0000_0024\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 25)
	       (:desc "    constant MASTER_LITE_RD_ADD_REG_ADDR   : std_logic_vector(31 downto 0) := x\"0000_0024\";" :col 45)
	       ("MASTER_LITE_RD_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 26)
	       (:desc "    constant MASTER_LITE_RD_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0028\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 26)
	       (:desc "    constant MASTER_LITE_RD_DATA_REG_ADDR  : std_logic_vector(31 downto 0) := x\"0000_0028\";" :col 45)
	       ("COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 27)
	       (:desc "    constant COUNT_LCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_002C\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 27)
	       (:desc "    constant COUNT_LCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_002C\";" :col 45)
	       ("PATTERN_COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 28)
	       (:desc "    constant PATTERN_COUNT_LCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0030\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 28)
	       (:desc "    constant PATTERN_COUNT_LCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0030\";" :col 45)
	       ("COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 29)
	       (:desc "    constant COUNT_RCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0034\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 29)
	       (:desc "    constant COUNT_RCH_REG_ADDR            : std_logic_vector(31 downto 0) := x\"0000_0034\";" :col 45)
	       ("PATTERN_COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 30)
	       (:desc "    constant PATTERN_COUNT_RCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0038\";" :col 13)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 30)
	       (:desc "    constant PATTERN_COUNT_RCH_REG_ADDR    : std_logic_vector(31 downto 0) := x\"0000_0038\";" :col 45)
	       ("read_control_reg" :file "../files/common/global_sim.vhd" :line 36)
	       (:desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 36)
	       (:desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 39)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 36)
	       (:desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 36)
	       (:desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 36)
	       (:desc "    procedure read_control_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 111)
	       ("read_status_reg" :file "../files/common/global_sim.vhd" :line 37)
	       (:desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 37)
	       (:desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 38)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 37)
	       (:desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 37)
	       (:desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 37)
	       (:desc "    procedure read_status_reg (signal bfm_in_r             : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 111)
	       ("read_version_reg" :file "../files/common/global_sim.vhd" :line 38)
	       (:desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 38)
	       (:desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 39)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 38)
	       (:desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 38)
	       (:desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 38)
	       (:desc "    procedure read_version_reg (signal bfm_in_r            : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 111)
	       ("read_counters" :file "../files/common/global_sim.vhd" :line 39)
	       (:desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 39)
	       (:desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 36)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 39)
	       (:desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 39)
	       (:desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 39)
	       (:desc "    procedure read_counters (signal bfm_in_r               : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 111)
	       ("read_master_lite_rd_data_reg" :file "../files/common/global_sim.vhd" :line 40)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 40)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 50)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 40)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 40)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 40)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out);" :col 111)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 39)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 43)
	       (:desc "    procedure write_control_reg(signal bfm_in_w              : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_converter_setup_reg" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 47)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 44)
	       (:desc "    procedure write_converter_setup_reg(signal bfm_in_w      : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_mm2s_size_reg" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 41)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 45)
	       (:desc "    procedure write_mm2s_size_reg(signal bfm_in_w            : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 52)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 46)
	       (:desc "    procedure write_master_lite_wr_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 50)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 47)
	       (:desc "    procedure write_master_lite_wr_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 51)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 48)
	       (:desc "    procedure write_master_lite_wr_data_reg(signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 52)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 49)
	       (:desc "    procedure write_master_lite_rd_setup_reg(signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 50)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 66)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 97)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 113)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 147)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 50)
	       (:desc "    procedure write_master_lite_rd_add_reg(signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant DATA : in std_logic_vector(31 downto 0));" :col 157)
	       ("write_control_reg_system_enable" :file "../files/common/global_sim.vhd" :line 53)
	       (:desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 53)
	       (:desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 54)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 53)
	       (:desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 68)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 53)
	       (:desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 99)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 53)
	       (:desc "    procedure write_control_reg_system_enable (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 115)
	       ("write_control_reg_system_stop" :file "../files/common/global_sim.vhd" :line 54)
	       (:desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 54)
	       (:desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 52)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 54)
	       (:desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 68)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 54)
	       (:desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 99)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 54)
	       (:desc "    procedure write_control_reg_system_stop (signal bfm_in_w   : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 115)
	       ("write_control_reg_soft_reset" :file "../files/common/global_sim.vhd" :line 55)
	       (:desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 55)
	       (:desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 51)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 55)
	       (:desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 68)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 55)
	       (:desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 99)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 55)
	       (:desc "    procedure write_control_reg_soft_reset (signal bfm_in_w    : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out);" :col 115)
	       ("write_master_lite_write_request" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 54)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 68)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 99)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 115)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 149)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 209)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 56)
	       (:desc "    procedure write_master_lite_write_request (signal bfm_in_w : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0); constant DATA : in std_logic_vector(31 downto 0));" :col 199)
	       ("write_master_lite_read_request" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 53)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 68)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 99)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 115)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 149)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 57)
	       (:desc "    procedure write_master_lite_read_request (signal bfm_in_w  : in s_common_response_w_in; signal bfm_out_w : out s_common_response_w_out; constant ADDR : in std_logic_vector(31 downto 0));" :col 159)
	       ("end_test_and_stop_clock" :file "../files/common/global_sim.vhd" :line 60)
	       (:desc "    procedure end_test_and_stop_clock(signal stop_clock : out std_logic);" :col 14)
	       ("stop_clock" :file "../files/common/global_sim.vhd" :line 60)
	       (:desc "    procedure end_test_and_stop_clock(signal stop_clock : out std_logic);" :col 45)
	       ("std_logic" :file "../files/common/global_sim.vhd" :line 60)
	       (:desc "    procedure end_test_and_stop_clock(signal stop_clock : out std_logic);" :col 62)
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 62)
	       (:desc "end package global_sim;" :col 12)
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 66)
	       (:desc "package body global_sim is" :col 13)
	       ("end_test_and_stop_clock" :file "../files/common/global_sim.vhd" :line 69)
	       (:desc "    procedure end_test_and_stop_clock (signal stop_clock : out std_logic) is" :col 14)
	       ("stop_clock" :file "../files/common/global_sim.vhd" :line 69)
	       (:desc "    procedure end_test_and_stop_clock (signal stop_clock : out std_logic) is" :col 46)
	       ("std_logic" :file "../files/common/global_sim.vhd" :line 69)
	       (:desc "    procedure end_test_and_stop_clock (signal stop_clock : out std_logic) is" :col 63)
	       ("false" :file "../files/common/global_sim.vhd" :line 71)
	       (:desc "        assert false report \"Test finished\" severity note;" :col 15)
	       ("note" :file "../files/common/global_sim.vhd" :line 71)
	       (:desc "        assert false report \"Test finished\" severity note;" :col 53)
	       ("stop_clock" :file "../files/common/global_sim.vhd" :line 72)
	       (:desc "        stop_clock <= '1';" :col 8)
	       ("end_test_and_stop_clock" :file "../files/common/global_sim.vhd" :line 74)
	       (:desc "    end end_test_and_stop_clock;" :col 8)
	       ("read_control_reg" :file "../files/common/global_sim.vhd" :line 78)
	       (:desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 78)
	       (:desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 39)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 78)
	       (:desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 53)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 78)
	       (:desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 84)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 78)
	       (:desc "    procedure read_control_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 100)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 80)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, CONTROL_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 80)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, CONTROL_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 80)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, CONTROL_REG_ADDR);" :col 33)
	       ("CONTROL_REG_ADDR" :file "../files/common/global_sim.vhd" :line 80)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, CONTROL_REG_ADDR);" :col 44)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 81)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("read_control_reg" :file "../files/common/global_sim.vhd" :line 82)
	       (:desc "    end procedure read_control_reg;" :col 18)
	       ("read_status_reg" :file "../files/common/global_sim.vhd" :line 85)
	       (:desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 85)
	       (:desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 38)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 85)
	       (:desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 52)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 85)
	       (:desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 83)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 85)
	       (:desc "    procedure read_status_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 99)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 87)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, STATUS_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 87)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, STATUS_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 87)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, STATUS_REG_ADDR);" :col 33)
	       ("STATUS_REG_ADDR" :file "../files/common/global_sim.vhd" :line 87)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, STATUS_REG_ADDR);" :col 44)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 88)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("read_status_reg" :file "../files/common/global_sim.vhd" :line 89)
	       (:desc "    end procedure read_status_reg;" :col 18)
	       ("read_version_reg" :file "../files/common/global_sim.vhd" :line 92)
	       (:desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 92)
	       (:desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 39)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 92)
	       (:desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 53)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 92)
	       (:desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 84)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 92)
	       (:desc "    procedure read_version_reg (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 100)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 94)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, VERSION_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 94)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, VERSION_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 94)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, VERSION_REG_ADDR);" :col 33)
	       ("VERSION_REG_ADDR" :file "../files/common/global_sim.vhd" :line 94)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, VERSION_REG_ADDR);" :col 44)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 95)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("read_version_reg" :file "../files/common/global_sim.vhd" :line 96)
	       (:desc "    end procedure read_version_reg;" :col 18)
	       ("read_counters" :file "../files/common/global_sim.vhd" :line 99)
	       (:desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 99)
	       (:desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 36)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 99)
	       (:desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 50)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 99)
	       (:desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 81)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 99)
	       (:desc "    procedure read_counters (signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 97)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 101)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_LCH_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 101)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_LCH_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 101)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_LCH_REG_ADDR);" :col 33)
	       ("COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 101)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_LCH_REG_ADDR);" :col 44)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 102)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_LCH_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 102)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_LCH_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 102)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_LCH_REG_ADDR);" :col 33)
	       ("PATTERN_COUNT_LCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 102)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_LCH_REG_ADDR);" :col 44)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 103)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_RCH_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 103)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_RCH_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 103)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_RCH_REG_ADDR);" :col 33)
	       ("COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 103)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, COUNT_RCH_REG_ADDR);" :col 44)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 104)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_RCH_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 104)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_RCH_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 104)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_RCH_REG_ADDR);" :col 33)
	       ("PATTERN_COUNT_RCH_REG_ADDR" :file "../files/common/global_sim.vhd" :line 104)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, PATTERN_COUNT_RCH_REG_ADDR);" :col 44)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 105)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("read_counters" :file "../files/common/global_sim.vhd" :line 106)
	       (:desc "    end procedure read_counters;" :col 18)
	       ("read_master_lite_rd_data_reg" :file "../files/common/global_sim.vhd" :line 109)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 14)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 109)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 50)
	       ("s_common_response_r_in" :file "../files/common/global_sim.vhd" :line 109)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 64)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 109)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 95)
	       ("s_common_response_r_out" :file "../files/common/global_sim.vhd" :line 109)
	       (:desc "    procedure read_master_lite_rd_data_reg(signal bfm_in_r : in s_common_response_r_in; signal bfm_out_r : out s_common_response_r_out) is" :col 111)
	       ("slave_read_sim" :file "../files/common/global_sim.vhd" :line 111)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, MASTER_LITE_RD_DATA_REG_ADDR);" :col 8)
	       ("bfm_in_r" :file "../files/common/global_sim.vhd" :line 111)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, MASTER_LITE_RD_DATA_REG_ADDR);" :col 23)
	       ("bfm_out_r" :file "../files/common/global_sim.vhd" :line 111)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, MASTER_LITE_RD_DATA_REG_ADDR);" :col 33)
	       ("MASTER_LITE_RD_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 111)
	       (:desc "        slave_read_sim(bfm_in_r, bfm_out_r, MASTER_LITE_RD_DATA_REG_ADDR);" :col 44)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 112)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("read_master_lite_rd_data_reg" :file "../files/common/global_sim.vhd" :line 113)
	       (:desc "    end procedure read_master_lite_rd_data_reg;" :col 18)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 117)
	       (:desc "    procedure write_control_reg (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 118)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 118)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 119)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 119)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 120)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 120)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 123)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONTROL_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 123)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONTROL_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 123)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONTROL_REG_ADDR, DATA);" :col 34)
	       ("CONTROL_REG_ADDR" :file "../files/common/global_sim.vhd" :line 123)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONTROL_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 123)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONTROL_REG_ADDR, DATA);" :col 63)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 124)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 125)
	       (:desc "    end procedure write_control_reg;" :col 18)
	       ("write_converter_setup_reg" :file "../files/common/global_sim.vhd" :line 128)
	       (:desc "    procedure write_converter_setup_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 129)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 129)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 130)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 130)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 131)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 131)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 134)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONVERTER_SETUP_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 134)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONVERTER_SETUP_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 134)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONVERTER_SETUP_REG_ADDR, DATA);" :col 34)
	       ("CONVERTER_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 134)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONVERTER_SETUP_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 134)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, CONVERTER_SETUP_REG_ADDR, DATA);" :col 71)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 135)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_converter_setup_reg" :file "../files/common/global_sim.vhd" :line 136)
	       (:desc "    end procedure write_converter_setup_reg;" :col 18)
	       ("write_mm2s_size_reg" :file "../files/common/global_sim.vhd" :line 139)
	       (:desc "    procedure write_mm2s_size_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 140)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 140)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 141)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 141)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 142)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 142)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 145)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MM2S_SIZE_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 145)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MM2S_SIZE_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 145)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MM2S_SIZE_REG_ADDR, DATA);" :col 34)
	       ("MM2S_SIZE_REG_ADDR" :file "../files/common/global_sim.vhd" :line 145)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MM2S_SIZE_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 145)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MM2S_SIZE_REG_ADDR, DATA);" :col 65)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 146)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_mm2s_size_reg" :file "../files/common/global_sim.vhd" :line 147)
	       (:desc "    end procedure write_mm2s_size_reg;" :col 18)
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 150)
	       (:desc "    procedure write_master_lite_wr_setup_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 151)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 151)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 152)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 152)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 153)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 153)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 156)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_SETUP_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 156)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_SETUP_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 156)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_SETUP_REG_ADDR, DATA);" :col 34)
	       ("MASTER_LITE_WR_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 156)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_SETUP_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 156)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_SETUP_REG_ADDR, DATA);" :col 76)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 157)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 158)
	       (:desc "    end procedure write_master_lite_wr_setup_reg;" :col 18)
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 161)
	       (:desc "    procedure write_master_lite_wr_add_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 162)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 162)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 163)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 163)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 164)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 164)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 167)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_ADDR_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 167)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_ADDR_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 167)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_ADDR_REG_ADDR, DATA);" :col 34)
	       ("MASTER_LITE_WR_ADDR_REG_ADDR" :file "../files/common/global_sim.vhd" :line 167)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_ADDR_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 167)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_ADDR_REG_ADDR, DATA);" :col 75)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 168)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 169)
	       (:desc "    end procedure write_master_lite_wr_add_reg;" :col 18)
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 172)
	       (:desc "    procedure write_master_lite_wr_data_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 173)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 173)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 174)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 174)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 175)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 175)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 178)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_DATA_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 178)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_DATA_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 178)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_DATA_REG_ADDR, DATA);" :col 34)
	       ("MASTER_LITE_WR_DATA_REG_ADDR" :file "../files/common/global_sim.vhd" :line 178)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_DATA_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 178)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_WR_DATA_REG_ADDR, DATA);" :col 75)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 179)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 180)
	       (:desc "    end procedure write_master_lite_wr_data_reg;" :col 18)
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 183)
	       (:desc "    procedure write_master_lite_rd_setup_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 184)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 184)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 185)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 185)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 186)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 186)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 189)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_SETUP_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 189)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_SETUP_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 189)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_SETUP_REG_ADDR, DATA);" :col 34)
	       ("MASTER_LITE_RD_SETUP_REG_ADDR" :file "../files/common/global_sim.vhd" :line 189)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_SETUP_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 189)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_SETUP_REG_ADDR, DATA);" :col 76)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 190)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 191)
	       (:desc "    end procedure write_master_lite_rd_setup_reg;" :col 18)
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 194)
	       (:desc "    procedure write_master_lite_rd_add_reg(" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 195)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 195)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 196)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 196)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 197)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 197)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("slave_write_sim" :file "../files/common/global_sim.vhd" :line 200)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_ADD_REG_ADDR, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 200)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_ADD_REG_ADDR, DATA);" :col 24)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 200)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_ADD_REG_ADDR, DATA);" :col 34)
	       ("MASTER_LITE_RD_ADD_REG_ADDR" :file "../files/common/global_sim.vhd" :line 200)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_ADD_REG_ADDR, DATA);" :col 45)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 200)
	       (:desc "        slave_write_sim(bfm_in_w, bfm_out_w, MASTER_LITE_RD_ADD_REG_ADDR, DATA);" :col 74)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 201)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 202)
	       (:desc "    end procedure write_master_lite_rd_add_reg;" :col 18)
	       ("write_control_reg_system_enable" :file "../files/common/global_sim.vhd" :line 206)
	       (:desc "    procedure write_control_reg_system_enable (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 207)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 207)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 208)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 208)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 31)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 211)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 211)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 26)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 211)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 36)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 212)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_control_reg_system_enable" :file "../files/common/global_sim.vhd" :line 213)
	       (:desc "    end procedure write_control_reg_system_enable;" :col 18)
	       ("write_control_reg_system_stop" :file "../files/common/global_sim.vhd" :line 216)
	       (:desc "    procedure write_control_reg_system_stop (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 217)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 217)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 218)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 218)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 31)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 221)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0000\");" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 221)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0000\");" :col 26)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 221)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"0000_0000\");" :col 36)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 222)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_control_reg_system_stop" :file "../files/common/global_sim.vhd" :line 223)
	       (:desc "    end procedure write_control_reg_system_stop;" :col 18)
	       ("write_control_reg_soft_reset" :file "../files/common/global_sim.vhd" :line 226)
	       (:desc "    procedure write_control_reg_soft_reset (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 227)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 227)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 228)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 228)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out" :col 31)
	       ("write_control_reg" :file "../files/common/global_sim.vhd" :line 231)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"8000_0000\");" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 231)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"8000_0000\");" :col 26)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 231)
	       (:desc "        write_control_reg(bfm_in_w, bfm_out_w, x\"8000_0000\");" :col 36)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 232)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_control_reg_soft_reset" :file "../files/common/global_sim.vhd" :line 233)
	       (:desc "    end procedure write_control_reg_soft_reset;" :col 18)
	       ("write_master_lite_write_request" :file "../files/common/global_sim.vhd" :line 236)
	       (:desc "    procedure write_master_lite_write_request (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 237)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 237)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 238)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 238)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 239)
	       (:desc "        constant ADDR    : in  std_logic_vector(31 downto 0);" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 239)
	       (:desc "        constant ADDR    : in  std_logic_vector(31 downto 0);" :col 31)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 240)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 240)
	       (:desc "        constant DATA    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("write_master_lite_wr_add_reg" :file "../files/common/global_sim.vhd" :line 243)
	       (:desc "        write_master_lite_wr_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 243)
	       (:desc "        write_master_lite_wr_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 37)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 243)
	       (:desc "        write_master_lite_wr_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 47)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 243)
	       (:desc "        write_master_lite_wr_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 58)
	       ("write_master_lite_wr_data_reg" :file "../files/common/global_sim.vhd" :line 244)
	       (:desc "        write_master_lite_wr_data_reg(bfm_in_w, bfm_out_w, DATA);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 244)
	       (:desc "        write_master_lite_wr_data_reg(bfm_in_w, bfm_out_w, DATA);" :col 38)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 244)
	       (:desc "        write_master_lite_wr_data_reg(bfm_in_w, bfm_out_w, DATA);" :col 48)
	       ("DATA" :file "../files/common/global_sim.vhd" :line 244)
	       (:desc "        write_master_lite_wr_data_reg(bfm_in_w, bfm_out_w, DATA);" :col 59)
	       ("write_master_lite_wr_setup_reg" :file "../files/common/global_sim.vhd" :line 245)
	       (:desc "        write_master_lite_wr_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 245)
	       (:desc "        write_master_lite_wr_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 39)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 245)
	       (:desc "        write_master_lite_wr_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 49)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 246)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_write_request" :file "../files/common/global_sim.vhd" :line 247)
	       (:desc "    end write_master_lite_write_request;" :col 8)
	       ("write_master_lite_read_request" :file "../files/common/global_sim.vhd" :line 250)
	       (:desc "    procedure write_master_lite_read_request (" :col 14)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 251)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 15)
	       ("s_common_response_w_in" :file "../files/common/global_sim.vhd" :line 251)
	       (:desc "        signal bfm_in_w  : in  s_common_response_w_in;" :col 31)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 252)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 15)
	       ("s_common_response_w_out" :file "../files/common/global_sim.vhd" :line 252)
	       (:desc "        signal bfm_out_w : out s_common_response_w_out;" :col 31)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 253)
	       (:desc "        constant ADDR    : in  std_logic_vector(31 downto 0)" :col 17)
	       ("std_logic_vector" :file "../files/common/global_sim.vhd" :line 253)
	       (:desc "        constant ADDR    : in  std_logic_vector(31 downto 0)" :col 31)
	       ("write_master_lite_rd_add_reg" :file "../files/common/global_sim.vhd" :line 256)
	       (:desc "        write_master_lite_rd_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 256)
	       (:desc "        write_master_lite_rd_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 37)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 256)
	       (:desc "        write_master_lite_rd_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 47)
	       ("ADDR" :file "../files/common/global_sim.vhd" :line 256)
	       (:desc "        write_master_lite_rd_add_reg(bfm_in_w, bfm_out_w, ADDR);" :col 58)
	       ("write_master_lite_rd_setup_reg" :file "../files/common/global_sim.vhd" :line 257)
	       (:desc "        write_master_lite_rd_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 8)
	       ("bfm_in_w" :file "../files/common/global_sim.vhd" :line 257)
	       (:desc "        write_master_lite_rd_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 39)
	       ("bfm_out_w" :file "../files/common/global_sim.vhd" :line 257)
	       (:desc "        write_master_lite_rd_setup_reg(bfm_in_w, bfm_out_w, x\"0000_0001\");" :col 49)
	       ("AXI_CLK_T" :file "../files/common/global_sim.vhd" :line 258)
	       (:desc "        wait for (5*AXI_CLK_T);" :col 20)
	       ("write_master_lite_read_request" :file "../files/common/global_sim.vhd" :line 259)
	       (:desc "    end write_master_lite_read_request;" :col 8)
	       ("global_sim" :file "../files/common/global_sim.vhd" :line 264)
	       (:desc "end package body global_sim;" :col 17)))
