#s(hash-table test equal data
	      (("foo" :file "../files/common/indent_misc.vhd" :line 14)
	       (:type "entity_declaration" :desc "entity foo is" :col 0 :parent nil)
	       ("indent" :file "../files/common/indent_misc.vhd" :line 21)
	       (:type "architecture_body" :desc "architecture indent of indent_test is" :col 0 :parent nil)
	       ("ARRAY_CONSTANT" :file "../files/common/indent_misc.vhd" :line 44)
	       (:type "constant_declaration" :desc "constant ARRAY_CONSTANT : array_type :=" :col 0 :parent "foo")
	       ("foo" :file "../files/common/indent_misc.vhd" :line 43)
	       (:type "package_body" :desc "package body foo is" :col 0 :parent nil)
	       ("test_multiline_expression" :file "../files/common/indent_misc.vhd" :line 57)
	       (:type "procedure_body" :desc "procedure test_multiline_expression is" :col 0 :parent "foo")
	       ("foo" :file "../files/common/indent_misc.vhd" :line 56)
	       (:type "package_body" :desc "package body foo is" :col 0 :parent nil)
	       ("LongTime" :file "../files/common/indent_misc.vhd" :line 81)
	       (:type "constant_interface_declaration" :desc "generic (LongTime : Time; ShortTime : Time);" :col 9 :parent "X_GATE")
	       ("ShortTime" :file "../files/common/indent_misc.vhd" :line 81)
	       (:type "constant_interface_declaration" :desc "generic (LongTime : Time; ShortTime : Time);" :col 26 :parent "X_GATE")
	       ("P1, P2, P3" :file "../files/common/indent_misc.vhd" :line 82)
	       (:type "signal_interface_declaration" :desc "port (P1, P2, P3 : inout BIT);" :col 6 :parent "X_GATE")
	       ("X_GATE" :file "../files/common/indent_misc.vhd" :line 80)
	       (:type "entity_declaration" :desc "entity X_GATE is" :col 0 :parent nil)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 86)
	       (:type "signal_declaration" :desc "signal A, B : BIT;" :col 0 :parent "STRUCTURE")
	       ("GB1, GB2" :file "../files/common/indent_misc.vhd" :line 90)
	       (:type "constant_interface_declaration" :desc "generic (GB1, GB2 : Time);" :col 9 :parent "STRUCTURE")
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 94)
	       (:type "signal_interface_declaration" :desc "port (PB1: in BIT; PB2 : inout BIT );" :col 6 :parent "STRUCTURE")
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 94)
	       (:type "signal_interface_declaration" :desc "port (PB1: in BIT; PB2 : inout BIT );" :col 19 :parent "STRUCTURE")
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 98)
	       (:type "constant_declaration" :desc "constant Delay : Time := 1 ms;" :col 0 :parent "STRUCTURE")
	       ("S1" :file "../files/common/indent_misc.vhd" :line 99)
	       (:type "signal_declaration" :desc "signal S1 : BIT;" :col 0 :parent "STRUCTURE")
	       ("STRUCTURE" :file "../files/common/indent_misc.vhd" :line 84)
	       (:type "architecture_body" :desc "architecture STRUCTURE of X_GATE is" :col 0 :parent nil)
	       ("P, Q, R" :file "../files/common/indent_misc.vhd" :line 107)
	       (:type "signal_declaration" :desc "signal P, Q, R: std_logic;" :col 0 :parent nil)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 110)
	       (:type "signal_interface_declaration" :desc "port(A, B: in std_logic;" :col 5 :parent nil)
	       ("C" :file "../files/common/indent_misc.vhd" :line 111)
	       (:type "signal_interface_declaration" :desc "C: out std_logic);" :col 0 :parent nil)
	       ("block_test" :file "../files/common/indent_misc.vhd" :line 120)
	       (:type "entity_declaration" :desc "entity block_test is" :col 0 :parent nil)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 124)
	       (:type "signal_declaration" :desc "signal A, B : BIT;" :col 0 :parent "arch")
	       ("GB1, GB2" :file "../files/common/indent_misc.vhd" :line 132)
	       (:type "constant_interface_declaration" :desc "generic (GB1, GB2 : Time);" :col 9 :parent "arch")
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 136)
	       (:type "signal_interface_declaration" :desc "port (PB1: in BIT; PB2 : inout BIT );" :col 6 :parent "arch")
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 136)
	       (:type "signal_interface_declaration" :desc "port (PB1: in BIT; PB2 : inout BIT );" :col 19 :parent "arch")
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 140)
	       (:type "constant_declaration" :desc "constant Delay : Time := 1 ms;" :col 0 :parent "arch")
	       ("S1" :file "../files/common/indent_misc.vhd" :line 141)
	       (:type "signal_declaration" :desc "signal S1 : BIT;" :col 0 :parent "arch")
	       ("arch" :file "../files/common/indent_misc.vhd" :line 122)
	       (:type "architecture_body" :desc "architecture arch of block_test is" :col 0 :parent nil)
	       ("clock, reset, button" :file "../files/common/indent_misc.vhd" :line 156)
	       (:type "signal_interface_declaration" :desc "    clock, reset, button : in  std_logic;" :col 4 :parent "traffic_light_fsm")
	       ("leds" :file "../files/common/indent_misc.vhd" :line 157)
	       (:type "signal_interface_declaration" :desc "    leds                 : out std_logic_vector(2 downto 0));  -- red, yellow, green" :col 4 :parent "traffic_light_fsm")
	       ("traffic_light_fsm" :file "../files/common/indent_misc.vhd" :line 154)
	       (:type "entity_declaration" :desc "entity traffic_light_fsm is" :col 0 :parent nil)
	       ("state_type" :file "../files/common/indent_misc.vhd" :line 161)
	       (:type "full_type_declaration" :desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 2 :parent "rtl")
	       ("state_reg, state_next" :file "../files/common/indent_misc.vhd" :line 162)
	       (:type "signal_declaration" :desc "  signal state_reg, state_next : state_type;" :col 2 :parent "rtl")
	       ("rtl" :file "../files/common/indent_misc.vhd" :line 160)
	       (:type "architecture_body" :desc "architecture rtl of traffic_light_fsm is" :col 0 :parent nil)))
