#s(hash-table test equal data
	      (("ieee" :file "../files/common/indent_misc.vhd" :line 7)
	       (:desc "library ieee, work;" :col 8)
	       ("work" :file "../files/common/indent_misc.vhd" :line 7)
	       (:desc "library ieee, work;" :col 14)
	       ("ieee" :file "../files/common/indent_misc.vhd" :line 9)
	       (:desc "use ieee.std_logic_1164.all;" :col 4)
	       ("std_logic_1164" :file "../files/common/indent_misc.vhd" :line 9)
	       (:desc "use ieee.std_logic_1164.all;" :col 9)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 14)
	       (:desc "entity foo is" :col 7)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 15)
	       (:desc "end entity foo;" :col 11)
	       ("indent" :file "../files/common/indent_misc.vhd" :line 21)
	       (:desc "architecture indent of indent_test is" :col 13)
	       ("indent_test" :file "../files/common/indent_misc.vhd" :line 21)
	       (:desc "architecture indent of indent_test is" :col 23)
	       ("var" :file "../files/common/indent_misc.vhd" :line 27)
	       (:desc "case var is" :col 5)
	       ("A" :file "../files/common/indent_misc.vhd" :line 28)
	       (:desc "when A =>" :col 5)
	       ("out" :file "../files/common/indent_misc.vhd" :line 29)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "../files/common/indent_misc.vhd" :line 29)
	       (:desc "out <= in;" :col 7)
	       ("B" :file "../files/common/indent_misc.vhd" :line 30)
	       (:desc "when B =>" :col 5)
	       ("out" :file "../files/common/indent_misc.vhd" :line 31)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "../files/common/indent_misc.vhd" :line 31)
	       (:desc "out <= in;" :col 7)
	       ("C" :file "../files/common/indent_misc.vhd" :line 32)
	       (:desc "when C =>" :col 5)
	       ("out" :file "../files/common/indent_misc.vhd" :line 33)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "../files/common/indent_misc.vhd" :line 33)
	       (:desc "out <= in;" :col 7)
	       ("out" :file "../files/common/indent_misc.vhd" :line 35)
	       (:desc "out <= in;" :col 0)
	       ("in" :file "../files/common/indent_misc.vhd" :line 35)
	       (:desc "out <= in;" :col 7)
	       ("indent" :file "../files/common/indent_misc.vhd" :line 39)
	       (:desc "end architecture indent;" :col 17)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 43)
	       (:desc "package body foo is" :col 13)
	       ("ARRAY_CONSTANT" :file "../files/common/indent_misc.vhd" :line 44)
	       (:desc "constant ARRAY_CONSTANT : array_type :=" :col 9)
	       ("array_type" :file "../files/common/indent_misc.vhd" :line 44)
	       (:desc "constant ARRAY_CONSTANT : array_type :=" :col 26)
	       ("VALUE_0" :file "../files/common/indent_misc.vhd" :line 46)
	       (:desc "VALUE_0," :col 0)
	       ("VALUE_1" :file "../files/common/indent_misc.vhd" :line 47)
	       (:desc "VALUE_1," :col 0)
	       ("VALUE_2" :file "../files/common/indent_misc.vhd" :line 48)
	       (:desc "VALUE_2," :col 0)
	       ("VALUE_3" :file "../files/common/indent_misc.vhd" :line 49)
	       (:desc "VALUE_3," :col 0)
	       ("VALUE_4" :file "../files/common/indent_misc.vhd" :line 50)
	       (:desc "VALUE_4" :col 0)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 52)
	       (:desc "end package body foo;" :col 17)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 56)
	       (:desc "package body foo is" :col 13)
	       ("test_multiline_expression" :file "../files/common/indent_misc.vhd" :line 57)
	       (:desc "procedure test_multiline_expression is" :col 10)
	       ("signal_out" :file "../files/common/indent_misc.vhd" :line 59)
	       (:desc "signal_out <= signal_in1 and" :col 0)
	       ("signal_in1" :file "../files/common/indent_misc.vhd" :line 59)
	       (:desc "signal_out <= signal_in1 and" :col 14)
	       ("signal_in2" :file "../files/common/indent_misc.vhd" :line 60)
	       (:desc "signal_in2 and" :col 0)
	       ("signal_in3" :file "../files/common/indent_misc.vhd" :line 61)
	       (:desc "signal_in3 and" :col 0)
	       ("signal_in4" :file "../files/common/indent_misc.vhd" :line 62)
	       (:desc "signal_in4;" :col 0)
	       ("test_multiline_expression" :file "../files/common/indent_misc.vhd" :line 63)
	       (:desc "end procedure test_multiline_expression;" :col 14)
	       ("foo" :file "../files/common/indent_misc.vhd" :line 64)
	       (:desc "end package body foo;" :col 17)
	       ("A1" :file "../files/common/indent_misc.vhd" :line 69)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 0)
	       ("OUT1" :file "../files/common/indent_misc.vhd" :line 69)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 69)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 24)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 70)
	       (:desc "LEVEL1 : block" :col 0)
	       ("A2" :file "../files/common/indent_misc.vhd" :line 72)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 0)
	       ("OUT2" :file "../files/common/indent_misc.vhd" :line 72)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 72)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 24)
	       ("A3" :file "../files/common/indent_misc.vhd" :line 73)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 0)
	       ("OUT3" :file "../files/common/indent_misc.vhd" :line 73)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 73)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 24)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 74)
	       (:desc "end block LEVEL1;" :col 10)
	       ("A1" :file "../files/common/indent_misc.vhd" :line 75)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 0)
	       ("OUT1" :file "../files/common/indent_misc.vhd" :line 75)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 75)
	       (:desc "A1: OUT1 <= '1' after 5 ns;" :col 24)
	       ("A2" :file "../files/common/indent_misc.vhd" :line 76)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 0)
	       ("OUT2" :file "../files/common/indent_misc.vhd" :line 76)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 76)
	       (:desc "A2: OUT2 <= '1' after 5 ns;" :col 24)
	       ("A3" :file "../files/common/indent_misc.vhd" :line 77)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 0)
	       ("OUT3" :file "../files/common/indent_misc.vhd" :line 77)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 4)
	       ("ns" :file "../files/common/indent_misc.vhd" :line 77)
	       (:desc "A3: OUT3 <= '0' after 4 ns;" :col 24)
	       ("X_GATE" :file "../files/common/indent_misc.vhd" :line 80)
	       (:desc "entity X_GATE is" :col 7)
	       ("LongTime" :file "../files/common/indent_misc.vhd" :line 81)
	       (:desc "generic (LongTime : Time; ShortTime : Time);" :col 9)
	       ("Time" :file "../files/common/indent_misc.vhd" :line 81)
	       (:desc "generic (LongTime : Time; ShortTime : Time);" :col 38)
	       ("ShortTime" :file "../files/common/indent_misc.vhd" :line 81)
	       (:desc "generic (LongTime : Time; ShortTime : Time);" :col 26)
	       ("P1, P2, P3" :file "../files/common/indent_misc.vhd" :line 82)
	       (:desc "port (P1, P2, P3 : inout BIT);" :col 6)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 82)
	       (:desc "port (P1, P2, P3 : inout BIT);" :col 25)
	       ("X_GATE" :file "../files/common/indent_misc.vhd" :line 83)
	       (:desc "end X_GATE;" :col 4)
	       ("STRUCTURE" :file "../files/common/indent_misc.vhd" :line 84)
	       (:desc "architecture STRUCTURE of X_GATE is" :col 13)
	       ("X_GATE" :file "../files/common/indent_misc.vhd" :line 84)
	       (:desc "architecture STRUCTURE of X_GATE is" :col 26)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 86)
	       (:desc "signal A, B : BIT;" :col 7)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 86)
	       (:desc "signal A, B : BIT;" :col 14)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 88)
	       (:desc "LEVEL1 : block" :col 0)
	       ("GB1, GB2" :file "../files/common/indent_misc.vhd" :line 90)
	       (:desc "generic (GB1, GB2 : Time);" :col 9)
	       ("Time" :file "../files/common/indent_misc.vhd" :line 90)
	       (:desc "generic (GB1, GB2 : Time);" :col 20)
	       ("GB1" :file "../files/common/indent_misc.vhd" :line 92)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 13)
	       ("LongTime" :file "../files/common/indent_misc.vhd" :line 92)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 20)
	       ("GB2" :file "../files/common/indent_misc.vhd" :line 92)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 30)
	       ("ShortTime" :file "../files/common/indent_misc.vhd" :line 92)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 37)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 94)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 6)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 94)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 31)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 94)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 19)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 96)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 10)
	       ("P1" :file "../files/common/indent_misc.vhd" :line 96)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 17)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 96)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 21)
	       ("B" :file "../files/common/indent_misc.vhd" :line 96)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 28)
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 98)
	       (:desc "constant Delay : Time := 1 ms;" :col 9)
	       ("Time" :file "../files/common/indent_misc.vhd" :line 98)
	       (:desc "constant Delay : Time := 1 ms;" :col 17)
	       ("ms" :file "../files/common/indent_misc.vhd" :line 98)
	       (:desc "constant Delay : Time := 1 ms;" :col 27)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 99)
	       (:desc "signal S1 : BIT;" :col 7)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 99)
	       (:desc "signal S1 : BIT;" :col 12)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 101)
	       (:desc "S1 <= PB1 after Delay;" :col 0)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 101)
	       (:desc "S1 <= PB1 after Delay;" :col 6)
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 101)
	       (:desc "S1 <= PB1 after Delay;" :col 16)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 102)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 0)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 102)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 7)
	       ("GB1" :file "../files/common/indent_misc.vhd" :line 102)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 16)
	       ("P1" :file "../files/common/indent_misc.vhd" :line 102)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 21)
	       ("GB2" :file "../files/common/indent_misc.vhd" :line 102)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 30)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 103)
	       (:desc "end block LEVEL1;" :col 10)
	       ("STRUCTURE" :file "../files/common/indent_misc.vhd" :line 104)
	       (:desc "end architecture STRUCTURE;" :col 17)
	       ("P, Q, R" :file "../files/common/indent_misc.vhd" :line 107)
	       (:desc "signal P, Q, R: std_logic;" :col 7)
	       ("std_logic" :file "../files/common/indent_misc.vhd" :line 107)
	       (:desc "signal P, Q, R: std_logic;" :col 16)
	       ("level1" :file "../files/common/indent_misc.vhd" :line 109)
	       (:desc "level1: block" :col 0)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 110)
	       (:desc "port(A, B: in std_logic;" :col 5)
	       ("std_logic" :file "../files/common/indent_misc.vhd" :line 110)
	       (:desc "port(A, B: in std_logic;" :col 14)
	       ("C" :file "../files/common/indent_misc.vhd" :line 111)
	       (:desc "C: out std_logic);" :col 0)
	       ("std_logic" :file "../files/common/indent_misc.vhd" :line 111)
	       (:desc "C: out std_logic);" :col 7)
	       ("A" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 9)
	       ("P" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 14)
	       ("B" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 17)
	       ("Q" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 22)
	       ("C" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 25)
	       ("R" :file "../files/common/indent_misc.vhd" :line 112)
	       (:desc "port map(A => P, B => Q, C => R);" :col 30)
	       ("C" :file "../files/common/indent_misc.vhd" :line 114)
	       (:desc "C <= A and B;" :col 0)
	       ("A" :file "../files/common/indent_misc.vhd" :line 114)
	       (:desc "C <= A and B;" :col 5)
	       ("B" :file "../files/common/indent_misc.vhd" :line 114)
	       (:desc "C <= A and B;" :col 11)
	       ("level1" :file "../files/common/indent_misc.vhd" :line 115)
	       (:desc "end block level1;" :col 10)
	       ("block_test" :file "../files/common/indent_misc.vhd" :line 120)
	       (:desc "entity block_test is" :col 7)
	       ("block_test" :file "../files/common/indent_misc.vhd" :line 121)
	       (:desc "end block_test;" :col 4)
	       ("arch" :file "../files/common/indent_misc.vhd" :line 122)
	       (:desc "architecture arch of block_test is" :col 13)
	       ("block_test" :file "../files/common/indent_misc.vhd" :line 122)
	       (:desc "architecture arch of block_test is" :col 21)
	       ("A, B" :file "../files/common/indent_misc.vhd" :line 124)
	       (:desc "signal A, B : BIT;" :col 7)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 124)
	       (:desc "signal A, B : BIT;" :col 14)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 127)
	       (:desc "S1 <= PB1 after Delay;" :col 0)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 127)
	       (:desc "S1 <= PB1 after Delay;" :col 6)
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 127)
	       (:desc "S1 <= PB1 after Delay;" :col 16)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 128)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 0)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 128)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 7)
	       ("GB1" :file "../files/common/indent_misc.vhd" :line 128)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 16)
	       ("P1" :file "../files/common/indent_misc.vhd" :line 128)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 21)
	       ("GB2" :file "../files/common/indent_misc.vhd" :line 128)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 30)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 130)
	       (:desc "LEVEL1 : block" :col 0)
	       ("GB1, GB2" :file "../files/common/indent_misc.vhd" :line 132)
	       (:desc "generic (GB1, GB2 : Time);" :col 9)
	       ("Time" :file "../files/common/indent_misc.vhd" :line 132)
	       (:desc "generic (GB1, GB2 : Time);" :col 20)
	       ("GB1" :file "../files/common/indent_misc.vhd" :line 134)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 13)
	       ("LongTime" :file "../files/common/indent_misc.vhd" :line 134)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 20)
	       ("GB2" :file "../files/common/indent_misc.vhd" :line 134)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 30)
	       ("ShortTime" :file "../files/common/indent_misc.vhd" :line 134)
	       (:desc "generic map (GB1 => LongTime, GB2 => ShortTime);" :col 37)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 136)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 6)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 136)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 31)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 136)
	       (:desc "port (PB1: in BIT; PB2 : inout BIT );" :col 19)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 138)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 10)
	       ("P1" :file "../files/common/indent_misc.vhd" :line 138)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 17)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 138)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 21)
	       ("B" :file "../files/common/indent_misc.vhd" :line 138)
	       (:desc "port map (PB1 => P1, PB2 => B);" :col 28)
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 140)
	       (:desc "constant Delay : Time := 1 ms;" :col 9)
	       ("Time" :file "../files/common/indent_misc.vhd" :line 140)
	       (:desc "constant Delay : Time := 1 ms;" :col 17)
	       ("ms" :file "../files/common/indent_misc.vhd" :line 140)
	       (:desc "constant Delay : Time := 1 ms;" :col 27)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 141)
	       (:desc "signal S1 : BIT;" :col 7)
	       ("BIT" :file "../files/common/indent_misc.vhd" :line 141)
	       (:desc "signal S1 : BIT;" :col 12)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 143)
	       (:desc "S1 <= PB1 after Delay;" :col 0)
	       ("PB1" :file "../files/common/indent_misc.vhd" :line 143)
	       (:desc "S1 <= PB1 after Delay;" :col 6)
	       ("Delay" :file "../files/common/indent_misc.vhd" :line 143)
	       (:desc "S1 <= PB1 after Delay;" :col 16)
	       ("PB2" :file "../files/common/indent_misc.vhd" :line 144)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 0)
	       ("S1" :file "../files/common/indent_misc.vhd" :line 144)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 7)
	       ("GB1" :file "../files/common/indent_misc.vhd" :line 144)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 16)
	       ("P1" :file "../files/common/indent_misc.vhd" :line 144)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 21)
	       ("GB2" :file "../files/common/indent_misc.vhd" :line 144)
	       (:desc "PB2 <= S1 after GB1, P1 after GB2;" :col 30)
	       ("LEVEL1" :file "../files/common/indent_misc.vhd" :line 145)
	       (:desc "end block LEVEL1;" :col 10)
	       ("arch" :file "../files/common/indent_misc.vhd" :line 146)
	       (:desc "end architecture arch;" :col 17)
	       ("ieee" :file "../files/common/indent_misc.vhd" :line 151)
	       (:desc "library ieee;" :col 8)
	       ("ieee" :file "../files/common/indent_misc.vhd" :line 152)
	       (:desc "use ieee.std_logic_1164.all;" :col 4)
	       ("std_logic_1164" :file "../files/common/indent_misc.vhd" :line 152)
	       (:desc "use ieee.std_logic_1164.all;" :col 9)
	       ("traffic_light_fsm" :file "../files/common/indent_misc.vhd" :line 154)
	       (:desc "entity traffic_light_fsm is" :col 7)
	       ("clock, reset, button" :file "../files/common/indent_misc.vhd" :line 156)
	       (:desc "    clock, reset, button : in  std_logic;" :col 4)
	       ("std_logic" :file "../files/common/indent_misc.vhd" :line 156)
	       (:desc "    clock, reset, button : in  std_logic;" :col 31)
	       ("leds" :file "../files/common/indent_misc.vhd" :line 157)
	       (:desc "    leds                 : out std_logic_vector(2 downto 0));  -- red, yellow, green" :col 4)
	       ("std_logic_vector" :file "../files/common/indent_misc.vhd" :line 157)
	       (:desc "    leds                 : out std_logic_vector(2 downto 0));  -- red, yellow, green" :col 31)
	       ("traffic_light_fsm" :file "../files/common/indent_misc.vhd" :line 158)
	       (:desc "end entity traffic_light_fsm;" :col 11)
	       ("rtl" :file "../files/common/indent_misc.vhd" :line 160)
	       (:desc "architecture rtl of traffic_light_fsm is" :col 13)
	       ("traffic_light_fsm" :file "../files/common/indent_misc.vhd" :line 160)
	       (:desc "architecture rtl of traffic_light_fsm is" :col 20)
	       ("state_type" :file "../files/common/indent_misc.vhd" :line 161)
	       (:desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 7)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 161)
	       (:desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 22)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 161)
	       (:desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 27)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 161)
	       (:desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 35)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 161)
	       (:desc "  type state_type is (RED, YELLOW, GREEN, RED_YELLOW);" :col 42)
	       ("state_reg, state_next" :file "../files/common/indent_misc.vhd" :line 162)
	       (:desc "  signal state_reg, state_next : state_type;" :col 9)
	       ("state_type" :file "../files/common/indent_misc.vhd" :line 162)
	       (:desc "  signal state_reg, state_next : state_type;" :col 33)
	       ("REG" :file "../files/common/indent_misc.vhd" :line 165)
	       (:desc "  REG : process (clock, reset) is" :col 2)
	       ("clock" :file "../files/common/indent_misc.vhd" :line 165)
	       (:desc "  REG : process (clock, reset) is" :col 17)
	       ("reset" :file "../files/common/indent_misc.vhd" :line 165)
	       (:desc "  REG : process (clock, reset) is" :col 24)
	       ("reset" :file "../files/common/indent_misc.vhd" :line 167)
	       (:desc "    if reset = '1' then                 -- asynchronous reset (active low)" :col 7)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 168)
	       (:desc "      state_reg <= RED;" :col 6)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 168)
	       (:desc "      state_reg <= RED;" :col 19)
	       ("rising_edge" :file "../files/common/indent_misc.vhd" :line 169)
	       (:desc "    elsif rising_edge(clock) then       -- rising clock edge" :col 10)
	       ("clock" :file "../files/common/indent_misc.vhd" :line 169)
	       (:desc "    elsif rising_edge(clock) then       -- rising clock edge" :col 22)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 170)
	       (:desc "      state_reg <= state_next;" :col 6)
	       ("state_next" :file "../files/common/indent_misc.vhd" :line 170)
	       (:desc "      state_reg <= state_next;" :col 19)
	       ("REG" :file "../files/common/indent_misc.vhd" :line 172)
	       (:desc "  end process REG;" :col 14)
	       ("NSL" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 2)
	       ("state_next" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 8)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 22)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 38)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 50)
	       ("button" :file "../files/common/indent_misc.vhd" :line 174)
	       (:desc "  NSL : state_next <= RED_YELLOW when state_reg = RED and button = '1' else" :col 58)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 175)
	       (:desc "                      GREEN  when state_reg = RED_YELLOW else" :col 22)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 175)
	       (:desc "                      GREEN  when state_reg = RED_YELLOW else" :col 34)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 175)
	       (:desc "                      GREEN  when state_reg = RED_YELLOW else" :col 46)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 176)
	       (:desc "                      YELLOW when state_reg = GREEN and button = '1' else" :col 22)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 176)
	       (:desc "                      YELLOW when state_reg = GREEN and button = '1' else" :col 34)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 176)
	       (:desc "                      YELLOW when state_reg = GREEN and button = '1' else" :col 46)
	       ("button" :file "../files/common/indent_misc.vhd" :line 176)
	       (:desc "                      YELLOW when state_reg = GREEN and button = '1' else" :col 56)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 177)
	       (:desc "                      RED    when state_reg = YELLOW else" :col 22)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 177)
	       (:desc "                      RED    when state_reg = YELLOW else" :col 34)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 177)
	       (:desc "                      RED    when state_reg = YELLOW else" :col 46)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 178)
	       (:desc "                      state_reg;" :col 22)
	       ("OL" :file "../files/common/indent_misc.vhd" :line 180)
	       (:desc "  OL : with state_reg select" :col 2)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 180)
	       (:desc "  OL : with state_reg select" :col 12)
	       ("leds" :file "../files/common/indent_misc.vhd" :line 181)
	       (:desc "    leds <=" :col 4)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 182)
	       (:desc "    \"100\" when RED," :col 15)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 183)
	       (:desc "    \"110\" when RED_YELLOW," :col 15)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 184)
	       (:desc "    \"001\" when GREEN," :col 15)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 185)
	       (:desc "    \"010\" when YELLOW," :col 15)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 189)
	       (:desc "  with state_reg select" :col 7)
	       ("leds" :file "../files/common/indent_misc.vhd" :line 190)
	       (:desc "    leds <= \"100\" when RED," :col 4)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 190)
	       (:desc "    leds <= \"100\" when RED," :col 23)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 191)
	       (:desc "            \"110\" when RED_YELLOW," :col 23)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 192)
	       (:desc "            \"001\" when GREEN," :col 23)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 193)
	       (:desc "            \"010\" when YELLOW," :col 23)
	       ("state_reg" :file "../files/common/indent_misc.vhd" :line 197)
	       (:desc "  with state_reg select leds <= \"100\" when RED," :col 7)
	       ("leds" :file "../files/common/indent_misc.vhd" :line 197)
	       (:desc "  with state_reg select leds <= \"100\" when RED," :col 24)
	       ("RED" :file "../files/common/indent_misc.vhd" :line 197)
	       (:desc "  with state_reg select leds <= \"100\" when RED," :col 43)
	       ("RED_YELLOW" :file "../files/common/indent_misc.vhd" :line 198)
	       (:desc "                                \"110\" when RED_YELLOW," :col 43)
	       ("GREEN" :file "../files/common/indent_misc.vhd" :line 199)
	       (:desc "                                \"001\" when GREEN," :col 43)
	       ("YELLOW" :file "../files/common/indent_misc.vhd" :line 200)
	       (:desc "                                \"010\" when YELLOW," :col 43)
	       ("rtl" :file "../files/common/indent_misc.vhd" :line 203)
	       (:desc "end architecture rtl;" :col 17)))
