#s(hash-table test equal data
	      (("clk" :file "../files/common/sexp.vhd" :line 28)
	       (:type "signal_interface_declaration" :desc "        clk    : in std_logic;" :col 8 :parent "foo")
	       ("resetn" :file "../files/common/sexp.vhd" :line 29)
	       (:type "signal_interface_declaration" :desc "        resetn : in std_logic" :col 8 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 26)
	       (:type "entity_declaration" :desc "entity foo is" :col 0 :parent nil)
	       ("clk" :file "../files/common/sexp.vhd" :line 36)
	       (:type "signal_interface_declaration" :desc "        clk    : in std_logic;" :col 8 :parent "foo2")
	       ("resetn" :file "../files/common/sexp.vhd" :line 37)
	       (:type "signal_interface_declaration" :desc "        resetn : in std_logic" :col 8 :parent "foo2")
	       ("foo2" :file "../files/common/sexp.vhd" :line 34)
	       (:type "entity_declaration" :desc "entity foo2 is" :col 0 :parent nil)
	       ("soft_reset" :file "../files/common/sexp.vhd" :line 46)
	       (:type "signal_declaration" :desc "    signal soft_reset : std_logic;" :col 4 :parent "RTL")
	       ("clka" :file "../files/common/sexp.vhd" :line 50)
	       (:type "signal_interface_declaration" :desc "            clka  : in  std_logic;" :col 12 :parent "blk_mem_gen_0")
	       ("doutb" :file "../files/common/sexp.vhd" :line 51)
	       (:type "signal_interface_declaration" :desc "            doutb : out std_logic_vector(63 downto 0)" :col 12 :parent "blk_mem_gen_0")
	       ("blk_mem_gen_0" :file "../files/common/sexp.vhd" :line 48)
	       (:type "component_declaration" :desc "    component blk_mem_gen_0" :col 4 :parent "RTL")
	       ("bit_depth" :file "../files/common/sexp.vhd" :line 55)
	       (:type "constant_interface_declaration" :desc "    function clogb2 (bit_depth : integer) return integer is" :col 21 :parent "clogb2")
	       ("depth" :file "../files/common/sexp.vhd" :line 56)
	       (:type "variable_declaration" :desc "        variable depth : integer := bit_depth;" :col 8 :parent "clogb2")
	       ("count" :file "../files/common/sexp.vhd" :line 57)
	       (:type "variable_declaration" :desc "        variable count : integer := 1;" :col 8 :parent "clogb2")
	       ("clogb2" :file "../files/common/sexp.vhd" :line 55)
	       (:type "function_body" :desc "    function clogb2 (bit_depth : integer) return integer is" :col 4 :parent "RTL")
	       ("init_values" :file "../files/common/sexp.vhd" :line 78)
	       (:type "procedure_body" :desc "        procedure init_values is" :col 8 :parent "RTL")
	       ("RTL" :file "../files/common/sexp.vhd" :line 44)
	       (:type "architecture_body" :desc "architecture RTL of foo is" :col 0 :parent nil)
	       ("soft_reset" :file "../files/common/sexp.vhd" :line 98)
	       (:type "signal_declaration" :desc "    signal soft_reset : std_logic;" :col 4 :parent "RTL")
	       ("bit_depth" :file "../files/common/sexp.vhd" :line 100)
	       (:type "constant_interface_declaration" :desc "    function clogb2 (bit_depth : integer) return integer is" :col 21 :parent "clogb2")
	       ("depth" :file "../files/common/sexp.vhd" :line 101)
	       (:type "variable_declaration" :desc "        variable depth : integer := bit_depth;" :col 8 :parent "clogb2")
	       ("count" :file "../files/common/sexp.vhd" :line 102)
	       (:type "variable_declaration" :desc "        variable count : integer := 1;" :col 8 :parent "clogb2")
	       ("clogb2" :file "../files/common/sexp.vhd" :line 100)
	       (:type "function_body" :desc "    function clogb2 (bit_depth : integer) return integer is" :col 4 :parent "RTL")
	       ("init_values" :file "../files/common/sexp.vhd" :line 125)
	       (:type "procedure_body" :desc "        procedure init_values is" :col 8 :parent "RTL")
	       ("RTL" :file "../files/common/sexp.vhd" :line 96)
	       (:type "architecture_body" :desc "architecture RTL of foo is" :col 0 :parent nil)
	       ("common_in" :file "../files/common/sexp.vhd" :line 147)
	       (:type "signal_interface_declaration" :desc "        signal common_in   : in  mf_common_response_r_type_in" :col 8 :parent "foo2")
	       ("foo2" :file "../files/common/sexp.vhd" :line 146)
	       (:type "procedure_declaration" :desc "    procedure foo2(" :col 4 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 144)
	       (:type "package_declaration" :desc "package foo is" :col 0 :parent nil)
	       ("common_in" :file "../files/common/sexp.vhd" :line 155)
	       (:type "signal_interface_declaration" :desc "        signal common_in   : in  mf_common_response_r_type_in" :col 8 :parent "foo2")
	       ("foo2" :file "../files/common/sexp.vhd" :line 154)
	       (:type "procedure_declaration" :desc "    procedure foo2(" :col 4 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 152)
	       (:type "package_declaration" :desc "package foo is" :col 0 :parent nil)
	       ("common_in" :file "../files/common/sexp.vhd" :line 164)
	       (:type "signal_interface_declaration" :desc "        signal common_in   : in  mf_common_response_r_type_in" :col 8 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 163)
	       (:type "procedure_body" :desc "    procedure foo (" :col 4 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 161)
	       (:type "package_body" :desc "package body foo is" :col 0 :parent nil)
	       ("common_in" :file "../files/common/sexp.vhd" :line 176)
	       (:type "signal_interface_declaration" :desc "        signal common_in   : in  mf_common_response_r_type_in" :col 8 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 175)
	       (:type "procedure_body" :desc "    procedure foo (" :col 4 :parent "foo")
	       ("foo" :file "../files/common/sexp.vhd" :line 173)
	       (:type "package_body" :desc "package body foo is" :col 0 :parent nil)
	       ("foo" :file "../files/common/sexp.vhd" :line 186)
	       (:type "configuration_declaration" :desc "configuration foo of foo2 is" :col 0 :parent nil)
	       ("foo" :file "../files/common/sexp.vhd" :line 190)
	       (:type "configuration_declaration" :desc "configuration foo of foo2 is" :col 0 :parent nil)
	       ("foo" :file "../files/common/sexp.vhd" :line 196)
	       (:type "context_declaration" :desc "context foo is" :col 0 :parent nil)
	       ("foo" :file "../files/common/sexp.vhd" :line 200)
	       (:type "context_declaration" :desc "context foo is" :col 0 :parent nil)))
