#s(hash-table test equal data
	      (("stdlogic_1d" :file "../files/common/std_logic_1164-body.vhdl" :line 58)
	       (:type "full_type_declaration" :desc "  type stdlogic_1d is array (STD_ULOGIC) of STD_ULOGIC;" :col 2 :parent "std_logic_1164")
	       ("stdlogic_table" :file "../files/common/std_logic_1164-body.vhdl" :line 59)
	       (:type "full_type_declaration" :desc "  type stdlogic_table is array(STD_ULOGIC, STD_ULOGIC) of STD_ULOGIC;" :col 2 :parent "std_logic_1164")
	       ("resolution_table" :file "../files/common/std_logic_1164-body.vhdl" :line 64)
	       (:type "constant_declaration" :desc "  constant resolution_table : stdlogic_table := (" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 79)
	       (:type "constant_interface_declaration" :desc "  function resolved (s : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 21 :parent "resolved")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 80)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := 'Z';  -- weakest state default" :col 4 :parent "resolved")
	       ("resolved" :file "../files/common/std_logic_1164-body.vhdl" :line 79)
	       (:type "function_body" :desc "  function resolved (s : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("and_table" :file "../files/common/std_logic_1164-body.vhdl" :line 100)
	       (:type "constant_declaration" :desc "  constant and_table : stdlogic_table := (" :col 2 :parent "std_logic_1164")
	       ("or_table" :file "../files/common/std_logic_1164-body.vhdl" :line 116)
	       (:type "constant_declaration" :desc "  constant or_table : stdlogic_table := (" :col 2 :parent "std_logic_1164")
	       ("xor_table" :file "../files/common/std_logic_1164-body.vhdl" :line 132)
	       (:type "constant_declaration" :desc "  constant xor_table : stdlogic_table := (" :col 2 :parent "std_logic_1164")
	       ("not_table" :file "../files/common/std_logic_1164-body.vhdl" :line 148)
	       (:type "constant_declaration" :desc "  constant not_table : stdlogic_1d :=" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 158)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 18 :parent "\"and\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 158)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 34 :parent "\"and\"")
	       ("\"and\"" :file "../files/common/std_logic_1164-body.vhdl" :line 158)
	       (:type "function_body" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 163)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 19 :parent "\"nand\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 163)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 35 :parent "\"nand\"")
	       ("\"nand\"" :file "../files/common/std_logic_1164-body.vhdl" :line 163)
	       (:type "function_body" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 168)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 17 :parent "\"or\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 168)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 33 :parent "\"or\"")
	       ("\"or\"" :file "../files/common/std_logic_1164-body.vhdl" :line 168)
	       (:type "function_body" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 173)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 18 :parent "\"nor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 173)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 34 :parent "\"nor\"")
	       ("\"nor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 173)
	       (:type "function_body" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 178)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 18 :parent "\"xor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 178)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 34 :parent "\"xor\"")
	       ("\"xor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 178)
	       (:type "function_body" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 183)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 19 :parent "\"xnor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 183)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 35 :parent "\"xnor\"")
	       ("\"xnor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 183)
	       (:type "function_body" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 188)
	       (:type "constant_interface_declaration" :desc "  function \"not\" (l : STD_ULOGIC) return UX01 is" :col 18 :parent "\"not\"")
	       ("\"not\"" :file "../files/common/std_logic_1164-body.vhdl" :line 188)
	       (:type "function_body" :desc "  function \"not\" (l : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 196)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 18 :parent "\"and\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 197)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"and\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 198)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"and\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 199)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"and\"")
	       ("\"and\"" :file "../files/common/std_logic_1164-body.vhdl" :line 196)
	       (:type "function_body" :desc "  function \"and\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 216)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 19 :parent "\"nand\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 217)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"nand\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 218)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"nand\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 219)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"nand\"")
	       ("\"nand\"" :file "../files/common/std_logic_1164-body.vhdl" :line 216)
	       (:type "function_body" :desc "  function \"nand\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 236)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 17 :parent "\"or\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 237)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"or\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 238)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"or\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 239)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"or\"")
	       ("\"or\"" :file "../files/common/std_logic_1164-body.vhdl" :line 236)
	       (:type "function_body" :desc "  function \"or\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 256)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 18 :parent "\"nor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 257)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"nor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 258)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"nor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 259)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"nor\"")
	       ("\"nor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 256)
	       (:type "function_body" :desc "  function \"nor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 276)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 18 :parent "\"xor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 277)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"xor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 278)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"xor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 279)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"xor\"")
	       ("\"xor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 276)
	       (:type "function_body" :desc "  function \"xor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l, r" :file "../files/common/std_logic_1164-body.vhdl" :line 296)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 19 :parent "\"xnor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 297)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"xnor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 298)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"xnor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 299)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"xnor\"")
	       ("\"xnor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 296)
	       (:type "function_body" :desc "  function \"xnor\" (l, r : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 316)
	       (:type "constant_interface_declaration" :desc "  function \"not\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 18 :parent "\"not\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 317)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"not\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 318)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length) := (others => 'X');" :col 4 :parent "\"not\"")
	       ("\"not\"" :file "../files/common/std_logic_1164-body.vhdl" :line 316)
	       (:type "function_body" :desc "  function \"not\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 329)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 18 :parent "\"and\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 329)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 41 :parent "\"and\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 332)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"and\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 333)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"and\"")
	       ("\"and\"" :file "../files/common/std_logic_1164-body.vhdl" :line 329)
	       (:type "function_body" :desc "  function \"and\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 341)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 18 :parent "\"and\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 341)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 34 :parent "\"and\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 344)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"and\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 345)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"and\"")
	       ("\"and\"" :file "../files/common/std_logic_1164-body.vhdl" :line 341)
	       (:type "function_body" :desc "  function \"and\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 356)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 19 :parent "\"nand\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 356)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 42 :parent "\"nand\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 359)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"nand\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 360)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"nand\"")
	       ("\"nand\"" :file "../files/common/std_logic_1164-body.vhdl" :line 356)
	       (:type "function_body" :desc "  function \"nand\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 368)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 19 :parent "\"nand\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 368)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 35 :parent "\"nand\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 371)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"nand\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 372)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"nand\"")
	       ("\"nand\"" :file "../files/common/std_logic_1164-body.vhdl" :line 368)
	       (:type "function_body" :desc "  function \"nand\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 383)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 17 :parent "\"or\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 383)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 40 :parent "\"or\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 386)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"or\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 387)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"or\"")
	       ("\"or\"" :file "../files/common/std_logic_1164-body.vhdl" :line 383)
	       (:type "function_body" :desc "  function \"or\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 395)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 17 :parent "\"or\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 395)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 33 :parent "\"or\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 398)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"or\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 399)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"or\"")
	       ("\"or\"" :file "../files/common/std_logic_1164-body.vhdl" :line 395)
	       (:type "function_body" :desc "  function \"or\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 410)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 18 :parent "\"nor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 410)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 41 :parent "\"nor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 413)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"nor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 414)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"nor\"")
	       ("\"nor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 410)
	       (:type "function_body" :desc "  function \"nor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 422)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 18 :parent "\"nor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 422)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 34 :parent "\"nor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 425)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"nor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 426)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"nor\"")
	       ("\"nor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 422)
	       (:type "function_body" :desc "  function \"nor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 437)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 18 :parent "\"xor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 437)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 41 :parent "\"xor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 440)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"xor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 441)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"xor\"")
	       ("\"xor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 437)
	       (:type "function_body" :desc "  function \"xor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 449)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 18 :parent "\"xor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 449)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 34 :parent "\"xor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 452)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"xor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 453)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"xor\"")
	       ("\"xor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 449)
	       (:type "function_body" :desc "  function \"xor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 464)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 19 :parent "\"xnor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 464)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 42 :parent "\"xnor\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 467)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"xnor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 468)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"xnor\"")
	       ("\"xnor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 464)
	       (:type "function_body" :desc "  function \"xnor\" (l : STD_ULOGIC_VECTOR; r : STD_ULOGIC)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 476)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 19 :parent "\"xnor\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 476)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 35 :parent "\"xnor\"")
	       ("rv" :file "../files/common/std_logic_1164-body.vhdl" :line 479)
	       (:type "alias_declaration" :desc "    alias rv        : STD_ULOGIC_VECTOR (1 to r'length) is r;" :col 4 :parent "\"xnor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 480)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to r'length);" :col 4 :parent "\"xnor\"")
	       ("\"xnor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 476)
	       (:type "function_body" :desc "  function \"xnor\" (l : STD_ULOGIC; r : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 491)
	       (:type "constant_interface_declaration" :desc "  function \"and\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 18 :parent "\"and\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 492)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '1';" :col 4 :parent "\"and\"")
	       ("\"and\"" :file "../files/common/std_logic_1164-body.vhdl" :line 491)
	       (:type "function_body" :desc "  function \"and\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 503)
	       (:type "constant_interface_declaration" :desc "  function \"nand\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 19 :parent "\"nand\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 504)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '1';" :col 4 :parent "\"nand\"")
	       ("\"nand\"" :file "../files/common/std_logic_1164-body.vhdl" :line 503)
	       (:type "function_body" :desc "  function \"nand\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 515)
	       (:type "constant_interface_declaration" :desc "  function \"or\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 17 :parent "\"or\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 516)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '0';" :col 4 :parent "\"or\"")
	       ("\"or\"" :file "../files/common/std_logic_1164-body.vhdl" :line 515)
	       (:type "function_body" :desc "  function \"or\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 527)
	       (:type "constant_interface_declaration" :desc "  function \"nor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 18 :parent "\"nor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 528)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '0';" :col 4 :parent "\"nor\"")
	       ("\"nor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 527)
	       (:type "function_body" :desc "  function \"nor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 539)
	       (:type "constant_interface_declaration" :desc "  function \"xor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 18 :parent "\"xor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 540)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '0';" :col 4 :parent "\"xor\"")
	       ("\"xor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 539)
	       (:type "function_body" :desc "  function \"xor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 551)
	       (:type "constant_interface_declaration" :desc "  function \"xnor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 19 :parent "\"xnor\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 552)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC := '0';" :col 4 :parent "\"xnor\"")
	       ("\"xnor\"" :file "../files/common/std_logic_1164-body.vhdl" :line 551)
	       (:type "function_body" :desc "  function \"xnor\" (l : STD_ULOGIC_VECTOR) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 567)
	       (:type "constant_interface_declaration" :desc "  function \"sll\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 18 :parent "\"sll\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 567)
	       (:type "constant_interface_declaration" :desc "  function \"sll\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 41 :parent "\"sll\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 570)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"sll\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 571)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length) := (others => '0');" :col 4 :parent "\"sll\"")
	       ("\"sll\"" :file "../files/common/std_logic_1164-body.vhdl" :line 567)
	       (:type "function_body" :desc "  function \"sll\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 584)
	       (:type "constant_interface_declaration" :desc "  function \"srl\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 18 :parent "\"srl\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 584)
	       (:type "constant_interface_declaration" :desc "  function \"srl\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 41 :parent "\"srl\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 587)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"srl\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 588)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length) := (others => '0');" :col 4 :parent "\"srl\"")
	       ("\"srl\"" :file "../files/common/std_logic_1164-body.vhdl" :line 584)
	       (:type "function_body" :desc "  function \"srl\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 601)
	       (:type "constant_interface_declaration" :desc "  function \"rol\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 18 :parent "\"rol\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 601)
	       (:type "constant_interface_declaration" :desc "  function \"rol\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 41 :parent "\"rol\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 604)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"rol\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 605)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length);" :col 4 :parent "\"rol\"")
	       ("rm" :file "../files/common/std_logic_1164-body.vhdl" :line 606)
	       (:type "constant_declaration" :desc "    constant rm     : INTEGER := r mod l'length;" :col 4 :parent "\"rol\"")
	       ("\"rol\"" :file "../files/common/std_logic_1164-body.vhdl" :line 601)
	       (:type "function_body" :desc "  function \"rol\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 620)
	       (:type "constant_interface_declaration" :desc "  function \"ror\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 18 :parent "\"ror\"")
	       ("r" :file "../files/common/std_logic_1164-body.vhdl" :line 620)
	       (:type "constant_interface_declaration" :desc "  function \"ror\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 41 :parent "\"ror\"")
	       ("lv" :file "../files/common/std_logic_1164-body.vhdl" :line 623)
	       (:type "alias_declaration" :desc "    alias lv        : STD_ULOGIC_VECTOR (1 to l'length) is l;" :col 4 :parent "\"ror\"")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 624)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to l'length) := (others => '0');" :col 4 :parent "\"ror\"")
	       ("rm" :file "../files/common/std_logic_1164-body.vhdl" :line 625)
	       (:type "constant_declaration" :desc "    constant rm     : INTEGER := r mod l'length;" :col 4 :parent "\"ror\"")
	       ("\"ror\"" :file "../files/common/std_logic_1164-body.vhdl" :line 620)
	       (:type "function_body" :desc "  function \"ror\" (l : STD_ULOGIC_VECTOR; r : INTEGER)" :col 2 :parent "std_logic_1164")
	       ("logic_x01_table" :file "../files/common/std_logic_1164-body.vhdl" :line 639)
	       (:type "full_type_declaration" :desc "  type logic_x01_table is array (STD_ULOGIC'low to STD_ULOGIC'high) of X01;" :col 2 :parent "std_logic_1164")
	       ("logic_x01z_table" :file "../files/common/std_logic_1164-body.vhdl" :line 640)
	       (:type "full_type_declaration" :desc "  type logic_x01z_table is array (STD_ULOGIC'low to STD_ULOGIC'high) of X01Z;" :col 2 :parent "std_logic_1164")
	       ("logic_ux01_table" :file "../files/common/std_logic_1164-body.vhdl" :line 641)
	       (:type "full_type_declaration" :desc "  type logic_ux01_table is array (STD_ULOGIC'low to STD_ULOGIC'high) of UX01;" :col 2 :parent "std_logic_1164")
	       ("cvt_to_x01" :file "../files/common/std_logic_1164-body.vhdl" :line 653)
	       (:type "constant_declaration" :desc "  constant cvt_to_x01 : logic_x01_table := (" :col 2 :parent "std_logic_1164")
	       ("cvt_to_x01z" :file "../files/common/std_logic_1164-body.vhdl" :line 676)
	       (:type "constant_declaration" :desc "  constant cvt_to_x01z : logic_x01z_table := (" :col 2 :parent "std_logic_1164")
	       ("cvt_to_ux01" :file "../files/common/std_logic_1164-body.vhdl" :line 699)
	       (:type "constant_declaration" :desc "  constant cvt_to_ux01 : logic_ux01_table := (" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 714)
	       (:type "constant_interface_declaration" :desc "  function To_bit (s : STD_ULOGIC; xmap : BIT := '0') return BIT is" :col 19 :parent "To_bit")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 714)
	       (:type "constant_interface_declaration" :desc "  function To_bit (s : STD_ULOGIC; xmap : BIT := '0') return BIT is" :col 35 :parent "To_bit")
	       ("To_bit" :file "../files/common/std_logic_1164-body.vhdl" :line 714)
	       (:type "function_body" :desc "  function To_bit (s : STD_ULOGIC; xmap : BIT := '0') return BIT is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 723)
	       (:type "constant_interface_declaration" :desc "  function To_bitvector (s : STD_ULOGIC_VECTOR; xmap : BIT := '0')" :col 25 :parent "To_bitvector")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 723)
	       (:type "constant_interface_declaration" :desc "  function To_bitvector (s : STD_ULOGIC_VECTOR; xmap : BIT := '0')" :col 48 :parent "To_bitvector")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 726)
	       (:type "alias_declaration" :desc "    alias sv        : STD_ULOGIC_VECTOR (s'length-1 downto 0) is s;" :col 4 :parent "To_bitvector")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 727)
	       (:type "variable_declaration" :desc "    variable result : BIT_VECTOR (s'length-1 downto 0);" :col 4 :parent "To_bitvector")
	       ("To_bitvector" :file "../files/common/std_logic_1164-body.vhdl" :line 723)
	       (:type "function_body" :desc "  function To_bitvector (s : STD_ULOGIC_VECTOR; xmap : BIT := '0')" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 739)
	       (:type "constant_interface_declaration" :desc "  function To_StdULogic (b : BIT) return STD_ULOGIC is" :col 25 :parent "To_StdULogic")
	       ("To_StdULogic" :file "../files/common/std_logic_1164-body.vhdl" :line 739)
	       (:type "function_body" :desc "  function To_StdULogic (b : BIT) return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 747)
	       (:type "constant_interface_declaration" :desc "  function To_StdLogicVector (b : BIT_VECTOR)" :col 30 :parent "To_StdLogicVector")
	       ("bv" :file "../files/common/std_logic_1164-body.vhdl" :line 750)
	       (:type "alias_declaration" :desc "    alias bv        : BIT_VECTOR (b'length-1 downto 0) is b;" :col 4 :parent "To_StdLogicVector")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 751)
	       (:type "variable_declaration" :desc "    variable result : STD_LOGIC_VECTOR (b'length-1 downto 0);" :col 4 :parent "To_StdLogicVector")
	       ("To_StdLogicVector" :file "../files/common/std_logic_1164-body.vhdl" :line 747)
	       (:type "function_body" :desc "  function To_StdLogicVector (b : BIT_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 762)
	       (:type "constant_interface_declaration" :desc "  function To_StdLogicVector (s : STD_ULOGIC_VECTOR)" :col 30 :parent "To_StdLogicVector")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 765)
	       (:type "alias_declaration" :desc "    alias sv        : STD_ULOGIC_VECTOR (s'length-1 downto 0) is s;" :col 4 :parent "To_StdLogicVector")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 766)
	       (:type "variable_declaration" :desc "    variable result : STD_LOGIC_VECTOR (s'length-1 downto 0);" :col 4 :parent "To_StdLogicVector")
	       ("To_StdLogicVector" :file "../files/common/std_logic_1164-body.vhdl" :line 762)
	       (:type "function_body" :desc "  function To_StdLogicVector (s : STD_ULOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 774)
	       (:type "constant_interface_declaration" :desc "  function To_StdULogicVector (b : BIT_VECTOR)" :col 31 :parent "To_StdULogicVector")
	       ("bv" :file "../files/common/std_logic_1164-body.vhdl" :line 777)
	       (:type "alias_declaration" :desc "    alias bv        : BIT_VECTOR (b'length-1 downto 0) is b;" :col 4 :parent "To_StdULogicVector")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 778)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (b'length-1 downto 0);" :col 4 :parent "To_StdULogicVector")
	       ("To_StdULogicVector" :file "../files/common/std_logic_1164-body.vhdl" :line 774)
	       (:type "function_body" :desc "  function To_StdULogicVector (b : BIT_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 789)
	       (:type "constant_interface_declaration" :desc "  function To_StdULogicVector (s : STD_LOGIC_VECTOR)" :col 31 :parent "To_StdULogicVector")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 792)
	       (:type "alias_declaration" :desc "    alias sv        : STD_LOGIC_VECTOR (s'length-1 downto 0) is s;" :col 4 :parent "To_StdULogicVector")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 793)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (s'length-1 downto 0);" :col 4 :parent "To_StdULogicVector")
	       ("To_StdULogicVector" :file "../files/common/std_logic_1164-body.vhdl" :line 789)
	       (:type "function_body" :desc "  function To_StdULogicVector (s : STD_LOGIC_VECTOR)" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 806)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : STD_ULOGIC_VECTOR; xmap : STD_ULOGIC := '0')" :col 18 :parent "TO_01")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 806)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : STD_ULOGIC_VECTOR; xmap : STD_ULOGIC := '0')" :col 41 :parent "TO_01")
	       ("RESULT" :file "../files/common/std_logic_1164-body.vhdl" :line 809)
	       (:type "variable_declaration" :desc "    variable RESULT      : STD_ULOGIC_VECTOR(s'length-1 downto 0);" :col 4 :parent "TO_01")
	       ("BAD_ELEMENT" :file "../files/common/std_logic_1164-body.vhdl" :line 810)
	       (:type "variable_declaration" :desc "    variable BAD_ELEMENT : BOOLEAN := false;" :col 4 :parent "TO_01")
	       ("XS" :file "../files/common/std_logic_1164-body.vhdl" :line 811)
	       (:type "alias_declaration" :desc "    alias XS             : STD_ULOGIC_VECTOR(s'length-1 downto 0) is s;" :col 4 :parent "TO_01")
	       ("TO_01" :file "../files/common/std_logic_1164-body.vhdl" :line 806)
	       (:type "function_body" :desc "  function TO_01 (s : STD_ULOGIC_VECTOR; xmap : STD_ULOGIC := '0')" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 828)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : STD_ULOGIC; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 18 :parent "TO_01")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 828)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : STD_ULOGIC; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 34 :parent "TO_01")
	       ("TO_01" :file "../files/common/std_logic_1164-body.vhdl" :line 828)
	       (:type "function_body" :desc "  function TO_01 (s : STD_ULOGIC; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 837)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : BIT_VECTOR; xmap : STD_ULOGIC := '0')" :col 18 :parent "TO_01")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 837)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : BIT_VECTOR; xmap : STD_ULOGIC := '0')" :col 34 :parent "TO_01")
	       ("RESULT" :file "../files/common/std_logic_1164-body.vhdl" :line 840)
	       (:type "variable_declaration" :desc "    variable RESULT : STD_ULOGIC_VECTOR(s'length-1 downto 0);" :col 4 :parent "TO_01")
	       ("XS" :file "../files/common/std_logic_1164-body.vhdl" :line 841)
	       (:type "alias_declaration" :desc "    alias XS        : BIT_VECTOR(s'length-1 downto 0) is s;" :col 4 :parent "TO_01")
	       ("TO_01" :file "../files/common/std_logic_1164-body.vhdl" :line 837)
	       (:type "function_body" :desc "  function TO_01 (s : BIT_VECTOR; xmap : STD_ULOGIC := '0')" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 852)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : BIT; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 18 :parent "TO_01")
	       ("xmap" :file "../files/common/std_logic_1164-body.vhdl" :line 852)
	       (:type "constant_interface_declaration" :desc "  function TO_01 (s : BIT; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 27 :parent "TO_01")
	       ("TO_01" :file "../files/common/std_logic_1164-body.vhdl" :line 852)
	       (:type "function_body" :desc "  function TO_01 (s : BIT; xmap : STD_ULOGIC := '0') return STD_ULOGIC is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 862)
	       (:type "constant_interface_declaration" :desc "  function To_X01 (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 19 :parent "To_X01")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 863)
	       (:type "alias_declaration" :desc "    alias sv        : STD_ULOGIC_VECTOR (1 to s'length) is s;" :col 4 :parent "To_X01")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 864)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to s'length);" :col 4 :parent "To_X01")
	       ("To_X01" :file "../files/common/std_logic_1164-body.vhdl" :line 862)
	       (:type "function_body" :desc "  function To_X01 (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 872)
	       (:type "constant_interface_declaration" :desc "  function To_X01 (s : STD_ULOGIC) return X01 is" :col 19 :parent "To_X01")
	       ("To_X01" :file "../files/common/std_logic_1164-body.vhdl" :line 872)
	       (:type "function_body" :desc "  function To_X01 (s : STD_ULOGIC) return X01 is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 877)
	       (:type "constant_interface_declaration" :desc "  function To_X01 (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 19 :parent "To_X01")
	       ("bv" :file "../files/common/std_logic_1164-body.vhdl" :line 878)
	       (:type "alias_declaration" :desc "    alias bv        : BIT_VECTOR (1 to b'length) is b;" :col 4 :parent "To_X01")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 879)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to b'length);" :col 4 :parent "To_X01")
	       ("To_X01" :file "../files/common/std_logic_1164-body.vhdl" :line 877)
	       (:type "function_body" :desc "  function To_X01 (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 890)
	       (:type "constant_interface_declaration" :desc "  function To_X01 (b : BIT) return X01 is" :col 19 :parent "To_X01")
	       ("To_X01" :file "../files/common/std_logic_1164-body.vhdl" :line 890)
	       (:type "function_body" :desc "  function To_X01 (b : BIT) return X01 is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 900)
	       (:type "constant_interface_declaration" :desc "  function To_X01Z (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 20 :parent "To_X01Z")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 901)
	       (:type "alias_declaration" :desc "    alias sv        : STD_ULOGIC_VECTOR (1 to s'length) is s;" :col 4 :parent "To_X01Z")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 902)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to s'length);" :col 4 :parent "To_X01Z")
	       ("To_X01Z" :file "../files/common/std_logic_1164-body.vhdl" :line 900)
	       (:type "function_body" :desc "  function To_X01Z (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 910)
	       (:type "constant_interface_declaration" :desc "  function To_X01Z (s : STD_ULOGIC) return X01Z is" :col 20 :parent "To_X01Z")
	       ("To_X01Z" :file "../files/common/std_logic_1164-body.vhdl" :line 910)
	       (:type "function_body" :desc "  function To_X01Z (s : STD_ULOGIC) return X01Z is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 915)
	       (:type "constant_interface_declaration" :desc "  function To_X01Z (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 20 :parent "To_X01Z")
	       ("bv" :file "../files/common/std_logic_1164-body.vhdl" :line 916)
	       (:type "alias_declaration" :desc "    alias bv        : BIT_VECTOR (1 to b'length) is b;" :col 4 :parent "To_X01Z")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 917)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to b'length);" :col 4 :parent "To_X01Z")
	       ("To_X01Z" :file "../files/common/std_logic_1164-body.vhdl" :line 915)
	       (:type "function_body" :desc "  function To_X01Z (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 928)
	       (:type "constant_interface_declaration" :desc "  function To_X01Z (b : BIT) return X01Z is" :col 20 :parent "To_X01Z")
	       ("To_X01Z" :file "../files/common/std_logic_1164-body.vhdl" :line 928)
	       (:type "function_body" :desc "  function To_X01Z (b : BIT) return X01Z is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 938)
	       (:type "constant_interface_declaration" :desc "  function To_UX01 (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 20 :parent "To_UX01")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 939)
	       (:type "alias_declaration" :desc "    alias sv        : STD_ULOGIC_VECTOR (1 to s'length) is s;" :col 4 :parent "To_UX01")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 940)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to s'length);" :col 4 :parent "To_UX01")
	       ("To_UX01" :file "../files/common/std_logic_1164-body.vhdl" :line 938)
	       (:type "function_body" :desc "  function To_UX01 (s : STD_ULOGIC_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 948)
	       (:type "constant_interface_declaration" :desc "  function To_UX01 (s : STD_ULOGIC) return UX01 is" :col 20 :parent "To_UX01")
	       ("To_UX01" :file "../files/common/std_logic_1164-body.vhdl" :line 948)
	       (:type "function_body" :desc "  function To_UX01 (s : STD_ULOGIC) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 953)
	       (:type "constant_interface_declaration" :desc "  function To_UX01 (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 20 :parent "To_UX01")
	       ("bv" :file "../files/common/std_logic_1164-body.vhdl" :line 954)
	       (:type "alias_declaration" :desc "    alias bv        : BIT_VECTOR (1 to b'length) is b;" :col 4 :parent "To_UX01")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 955)
	       (:type "variable_declaration" :desc "    variable result : STD_ULOGIC_VECTOR (1 to b'length);" :col 4 :parent "To_UX01")
	       ("To_UX01" :file "../files/common/std_logic_1164-body.vhdl" :line 953)
	       (:type "function_body" :desc "  function To_UX01 (b : BIT_VECTOR) return STD_ULOGIC_VECTOR is" :col 2 :parent "std_logic_1164")
	       ("b" :file "../files/common/std_logic_1164-body.vhdl" :line 966)
	       (:type "constant_interface_declaration" :desc "  function To_UX01 (b : BIT) return UX01 is" :col 20 :parent "To_UX01")
	       ("To_UX01" :file "../files/common/std_logic_1164-body.vhdl" :line 966)
	       (:type "function_body" :desc "  function To_UX01 (b : BIT) return UX01 is" :col 2 :parent "std_logic_1164")
	       ("l" :file "../files/common/std_logic_1164-body.vhdl" :line 974)
	       (:type "constant_interface_declaration" :desc "  function \"??\" (l : STD_ULOGIC) return BOOLEAN is" :col 17 :parent "\"??\"")
	       ("\"??\"" :file "../files/common/std_logic_1164-body.vhdl" :line 974)
	       (:type "function_body" :desc "  function \"??\" (l : STD_ULOGIC) return BOOLEAN is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 982)
	       (:type "signal_interface_declaration" :desc "  function rising_edge (signal s : STD_ULOGIC) return BOOLEAN is" :col 24 :parent "rising_edge")
	       ("rising_edge" :file "../files/common/std_logic_1164-body.vhdl" :line 982)
	       (:type "function_body" :desc "  function rising_edge (signal s : STD_ULOGIC) return BOOLEAN is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 988)
	       (:type "signal_interface_declaration" :desc "  function falling_edge (signal s : STD_ULOGIC) return BOOLEAN is" :col 25 :parent "falling_edge")
	       ("falling_edge" :file "../files/common/std_logic_1164-body.vhdl" :line 988)
	       (:type "function_body" :desc "  function falling_edge (signal s : STD_ULOGIC) return BOOLEAN is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 997)
	       (:type "constant_interface_declaration" :desc "  function Is_X (s : STD_ULOGIC_VECTOR) return BOOLEAN is" :col 17 :parent "Is_X")
	       ("Is_X" :file "../files/common/std_logic_1164-body.vhdl" :line 997)
	       (:type "function_body" :desc "  function Is_X (s : STD_ULOGIC_VECTOR) return BOOLEAN is" :col 2 :parent "std_logic_1164")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 1008)
	       (:type "constant_interface_declaration" :desc "  function Is_X (s : STD_ULOGIC) return BOOLEAN is" :col 17 :parent "Is_X")
	       ("Is_X" :file "../files/common/std_logic_1164-body.vhdl" :line 1008)
	       (:type "function_body" :desc "  function Is_X (s : STD_ULOGIC) return BOOLEAN is" :col 2 :parent "std_logic_1164")
	       ("value" :file "../files/common/std_logic_1164-body.vhdl" :line 1021)
	       (:type "constant_interface_declaration" :desc "  function TO_OSTRING (value : STD_ULOGIC_VECTOR) return STRING is" :col 23 :parent "TO_OSTRING")
	       ("result_length" :file "../files/common/std_logic_1164-body.vhdl" :line 1022)
	       (:type "constant_declaration" :desc "    constant result_length : NATURAL := (value'length+2)/3;" :col 4 :parent "TO_OSTRING")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1023)
	       (:type "variable_declaration" :desc "    variable pad           : STD_ULOGIC_VECTOR(1 to result_length*3 - value'length);" :col 4 :parent "TO_OSTRING")
	       ("padded_value" :file "../files/common/std_logic_1164-body.vhdl" :line 1024)
	       (:type "variable_declaration" :desc "    variable padded_value  : STD_ULOGIC_VECTOR(1 to result_length*3);" :col 4 :parent "TO_OSTRING")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 1025)
	       (:type "variable_declaration" :desc "    variable result        : STRING(1 to result_length);" :col 4 :parent "TO_OSTRING")
	       ("tri" :file "../files/common/std_logic_1164-body.vhdl" :line 1026)
	       (:type "variable_declaration" :desc "    variable tri           : STD_ULOGIC_VECTOR(1 to 3);" :col 4 :parent "TO_OSTRING")
	       ("TO_OSTRING" :file "../files/common/std_logic_1164-body.vhdl" :line 1021)
	       (:type "function_body" :desc "  function TO_OSTRING (value : STD_ULOGIC_VECTOR) return STRING is" :col 2 :parent "std_logic_1164")
	       ("value" :file "../files/common/std_logic_1164-body.vhdl" :line 1052)
	       (:type "constant_interface_declaration" :desc "  function TO_HSTRING (value : STD_ULOGIC_VECTOR) return STRING is" :col 23 :parent "TO_HSTRING")
	       ("result_length" :file "../files/common/std_logic_1164-body.vhdl" :line 1053)
	       (:type "constant_declaration" :desc "    constant result_length : NATURAL := (value'length+3)/4;" :col 4 :parent "TO_HSTRING")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1054)
	       (:type "variable_declaration" :desc "    variable pad           : STD_ULOGIC_VECTOR(1 to result_length*4 - value'length);" :col 4 :parent "TO_HSTRING")
	       ("padded_value" :file "../files/common/std_logic_1164-body.vhdl" :line 1055)
	       (:type "variable_declaration" :desc "    variable padded_value  : STD_ULOGIC_VECTOR(1 to result_length*4);" :col 4 :parent "TO_HSTRING")
	       ("result" :file "../files/common/std_logic_1164-body.vhdl" :line 1056)
	       (:type "variable_declaration" :desc "    variable result        : STRING(1 to result_length);" :col 4 :parent "TO_HSTRING")
	       ("quad" :file "../files/common/std_logic_1164-body.vhdl" :line 1057)
	       (:type "variable_declaration" :desc "    variable quad          : STD_ULOGIC_VECTOR(1 to 4);" :col 4 :parent "TO_HSTRING")
	       ("TO_HSTRING" :file "../files/common/std_logic_1164-body.vhdl" :line 1052)
	       (:type "function_body" :desc "  function TO_HSTRING (value : STD_ULOGIC_VECTOR) return STRING is" :col 2 :parent "std_logic_1164")
	       ("MVL9plus" :file "../files/common/std_logic_1164-body.vhdl" :line 1093)
	       (:type "full_type_declaration" :desc "  type MVL9plus is ('U', 'X', '0', '1', 'Z', 'W', 'L', 'H', '-', error);" :col 2 :parent "std_logic_1164")
	       ("char_indexed_by_MVL9" :file "../files/common/std_logic_1164-body.vhdl" :line 1094)
	       (:type "full_type_declaration" :desc "  type char_indexed_by_MVL9 is array (STD_ULOGIC) of CHARACTER;" :col 2 :parent "std_logic_1164")
	       ("MVL9_indexed_by_char" :file "../files/common/std_logic_1164-body.vhdl" :line 1095)
	       (:type "full_type_declaration" :desc "  type MVL9_indexed_by_char is array (CHARACTER) of STD_ULOGIC;" :col 2 :parent "std_logic_1164")
	       ("MVL9plus_indexed_by_char" :file "../files/common/std_logic_1164-body.vhdl" :line 1096)
	       (:type "full_type_declaration" :desc "  type MVL9plus_indexed_by_char is array (CHARACTER) of MVL9plus;" :col 2 :parent "std_logic_1164")
	       ("MVL9_to_char" :file "../files/common/std_logic_1164-body.vhdl" :line 1097)
	       (:type "constant_declaration" :desc "  constant MVL9_to_char : char_indexed_by_MVL9 := \"UX01ZWLH-\";" :col 2 :parent "std_logic_1164")
	       ("char_to_MVL9" :file "../files/common/std_logic_1164-body.vhdl" :line 1098)
	       (:type "constant_declaration" :desc "  constant char_to_MVL9 : MVL9_indexed_by_char :=" :col 2 :parent "std_logic_1164")
	       ("char_to_MVL9plus" :file "../files/common/std_logic_1164-body.vhdl" :line 1101)
	       (:type "constant_declaration" :desc "  constant char_to_MVL9plus : MVL9plus_indexed_by_char :=" :col 2 :parent "std_logic_1164")
	       ("NBSP" :file "../files/common/std_logic_1164-body.vhdl" :line 1105)
	       (:type "constant_declaration" :desc "  constant NBSP : CHARACTER := CHARACTER'val(160);  -- space character" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1110)
	       (:type "variable_declaration" :desc "    variable c : CHARACTER;" :col 4 :parent "skip_whitespace")
	       ("left" :file "../files/common/std_logic_1164-body.vhdl" :line 1111)
	       (:type "variable_declaration" :desc "    variable left : positive;" :col 4 :parent "skip_whitespace")
	       ("skip_whitespace" :file "../files/common/std_logic_1164-body.vhdl" :line 1108)
	       (:type "procedure_body" :desc "  procedure skip_whitespace (" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1126)
	       (:type "variable_declaration" :desc "    variable c      : CHARACTER;" :col 4 :parent "READ")
	       ("readOk" :file "../files/common/std_logic_1164-body.vhdl" :line 1127)
	       (:type "variable_declaration" :desc "    variable readOk : BOOLEAN;" :col 4 :parent "READ")
	       ("READ" :file "../files/common/std_logic_1164-body.vhdl" :line 1124)
	       (:type "procedure_body" :desc "  procedure READ (L    : inout LINE; VALUE : out STD_ULOGIC;" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1146)
	       (:type "variable_declaration" :desc "    variable c      : CHARACTER;" :col 4 :parent "READ")
	       ("mv" :file "../files/common/std_logic_1164-body.vhdl" :line 1147)
	       (:type "variable_declaration" :desc "    variable mv     : STD_ULOGIC_VECTOR(0 to VALUE'length-1);" :col 4 :parent "READ")
	       ("readOk" :file "../files/common/std_logic_1164-body.vhdl" :line 1148)
	       (:type "variable_declaration" :desc "    variable readOk : BOOLEAN;" :col 4 :parent "READ")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1149)
	       (:type "variable_declaration" :desc "    variable i      : INTEGER;" :col 4 :parent "READ")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1150)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "READ")
	       ("READ" :file "../files/common/std_logic_1164-body.vhdl" :line 1144)
	       (:type "procedure_body" :desc "  procedure READ (L    : inout LINE; VALUE : out STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1192)
	       (:type "variable_declaration" :desc "    variable c      : CHARACTER;" :col 4 :parent "READ")
	       ("readOk" :file "../files/common/std_logic_1164-body.vhdl" :line 1193)
	       (:type "variable_declaration" :desc "    variable readOk : BOOLEAN;" :col 4 :parent "READ")
	       ("READ" :file "../files/common/std_logic_1164-body.vhdl" :line 1191)
	       (:type "procedure_body" :desc "  procedure READ (L : inout LINE; VALUE : out STD_ULOGIC) is" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1214)
	       (:type "variable_declaration" :desc "    variable c      : CHARACTER;" :col 4 :parent "READ")
	       ("readOk" :file "../files/common/std_logic_1164-body.vhdl" :line 1215)
	       (:type "variable_declaration" :desc "    variable readOk : BOOLEAN;" :col 4 :parent "READ")
	       ("mv" :file "../files/common/std_logic_1164-body.vhdl" :line 1216)
	       (:type "variable_declaration" :desc "    variable mv     : STD_ULOGIC_VECTOR(0 to VALUE'length-1);" :col 4 :parent "READ")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1217)
	       (:type "variable_declaration" :desc "    variable i      : INTEGER;" :col 4 :parent "READ")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1218)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "READ")
	       ("READ" :file "../files/common/std_logic_1164-body.vhdl" :line 1213)
	       (:type "procedure_body" :desc "  procedure READ (L : inout LINE; VALUE : out STD_ULOGIC_VECTOR) is" :col 2 :parent "std_logic_1164")
	       ("VALUE" :file "../files/common/std_logic_1164-body.vhdl" :line 1264)
	       (:type "constant_interface_declaration" :desc "  procedure WRITE (L         : inout LINE; VALUE : in STD_ULOGIC;" :col 43 :parent "WRITE")
	       ("JUSTIFIED" :file "../files/common/std_logic_1164-body.vhdl" :line 1265)
	       (:type "constant_interface_declaration" :desc "                   JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 19 :parent "WRITE")
	       ("FIELD" :file "../files/common/std_logic_1164-body.vhdl" :line 1265)
	       (:type "constant_interface_declaration" :desc "                   JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 52 :parent "WRITE")
	       ("WRITE" :file "../files/common/std_logic_1164-body.vhdl" :line 1264)
	       (:type "procedure_body" :desc "  procedure WRITE (L         : inout LINE; VALUE : in STD_ULOGIC;" :col 2 :parent "std_logic_1164")
	       ("VALUE" :file "../files/common/std_logic_1164-body.vhdl" :line 1270)
	       (:type "constant_interface_declaration" :desc "  procedure WRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 43 :parent "WRITE")
	       ("JUSTIFIED" :file "../files/common/std_logic_1164-body.vhdl" :line 1271)
	       (:type "constant_interface_declaration" :desc "                   JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 19 :parent "WRITE")
	       ("FIELD" :file "../files/common/std_logic_1164-body.vhdl" :line 1271)
	       (:type "constant_interface_declaration" :desc "                   JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 52 :parent "WRITE")
	       ("s" :file "../files/common/std_logic_1164-body.vhdl" :line 1272)
	       (:type "variable_declaration" :desc "    variable s : STRING(1 to VALUE'length);" :col 4 :parent "WRITE")
	       ("m" :file "../files/common/std_logic_1164-body.vhdl" :line 1273)
	       (:type "alias_declaration" :desc "    alias m    : STD_ULOGIC_VECTOR(1 to VALUE'length) is VALUE;" :col 4 :parent "WRITE")
	       ("WRITE" :file "../files/common/std_logic_1164-body.vhdl" :line 1270)
	       (:type "procedure_body" :desc "  procedure WRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("C" :file "../files/common/std_logic_1164-body.vhdl" :line 1281)
	       (:type "constant_interface_declaration" :desc "  procedure Char2TriBits (C           : in  CHARACTER;" :col 26 :parent "Char2TriBits")
	       ("ISSUE_ERROR" :file "../files/common/std_logic_1164-body.vhdl" :line 1284)
	       (:type "constant_interface_declaration" :desc "                          ISSUE_ERROR : in  BOOLEAN) is" :col 26 :parent "Char2TriBits")
	       ("Char2TriBits" :file "../files/common/std_logic_1164-body.vhdl" :line 1281)
	       (:type "procedure_body" :desc "  procedure Char2TriBits (C           : in  CHARACTER;" :col 2 :parent "std_logic_1164")
	       ("ok" :file "../files/common/std_logic_1164-body.vhdl" :line 1309)
	       (:type "variable_declaration" :desc "    variable ok  : BOOLEAN;" :col 4 :parent "OREAD")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1310)
	       (:type "variable_declaration" :desc "    variable c   : CHARACTER;" :col 4 :parent "OREAD")
	       ("ne" :file "../files/common/std_logic_1164-body.vhdl" :line 1311)
	       (:type "constant_declaration" :desc "    constant ne  : INTEGER := (VALUE'length+2)/3;" :col 4 :parent "OREAD")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1312)
	       (:type "constant_declaration" :desc "    constant pad : INTEGER := ne*3 - VALUE'length;" :col 4 :parent "OREAD")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 1313)
	       (:type "variable_declaration" :desc "    variable sv  : STD_ULOGIC_VECTOR(0 to ne*3 - 1);" :col 4 :parent "OREAD")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1314)
	       (:type "variable_declaration" :desc "    variable i   : INTEGER;" :col 4 :parent "OREAD")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1315)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "OREAD")
	       ("OREAD" :file "../files/common/std_logic_1164-body.vhdl" :line 1307)
	       (:type "procedure_body" :desc "  procedure OREAD (L    : inout LINE; VALUE : out STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1362)
	       (:type "variable_declaration" :desc "    variable c   : CHARACTER;" :col 4 :parent "OREAD")
	       ("ok" :file "../files/common/std_logic_1164-body.vhdl" :line 1363)
	       (:type "variable_declaration" :desc "    variable ok  : BOOLEAN;" :col 4 :parent "OREAD")
	       ("ne" :file "../files/common/std_logic_1164-body.vhdl" :line 1364)
	       (:type "constant_declaration" :desc "    constant ne  : INTEGER := (VALUE'length+2)/3;" :col 4 :parent "OREAD")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1365)
	       (:type "constant_declaration" :desc "    constant pad : INTEGER := ne*3 - VALUE'length;" :col 4 :parent "OREAD")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 1366)
	       (:type "variable_declaration" :desc "    variable sv  : STD_ULOGIC_VECTOR(0 to ne*3 - 1);" :col 4 :parent "OREAD")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1367)
	       (:type "variable_declaration" :desc "    variable i   : INTEGER;" :col 4 :parent "OREAD")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1368)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "OREAD")
	       ("OREAD" :file "../files/common/std_logic_1164-body.vhdl" :line 1361)
	       (:type "procedure_body" :desc "  procedure OREAD (L : inout LINE; VALUE : out STD_ULOGIC_VECTOR) is" :col 2 :parent "std_logic_1164")
	       ("C" :file "../files/common/std_logic_1164-body.vhdl" :line 1416)
	       (:type "constant_interface_declaration" :desc "  procedure Char2QuadBits (C           :     CHARACTER;" :col 27 :parent "Char2QuadBits")
	       ("ISSUE_ERROR" :file "../files/common/std_logic_1164-body.vhdl" :line 1419)
	       (:type "constant_interface_declaration" :desc "                           ISSUE_ERROR : in  BOOLEAN) is" :col 27 :parent "Char2QuadBits")
	       ("Char2QuadBits" :file "../files/common/std_logic_1164-body.vhdl" :line 1416)
	       (:type "procedure_body" :desc "  procedure Char2QuadBits (C           :     CHARACTER;" :col 2 :parent "std_logic_1164")
	       ("ok" :file "../files/common/std_logic_1164-body.vhdl" :line 1452)
	       (:type "variable_declaration" :desc "    variable ok  : BOOLEAN;" :col 4 :parent "HREAD")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1453)
	       (:type "variable_declaration" :desc "    variable c   : CHARACTER;" :col 4 :parent "HREAD")
	       ("ne" :file "../files/common/std_logic_1164-body.vhdl" :line 1454)
	       (:type "constant_declaration" :desc "    constant ne  : INTEGER := (VALUE'length+3)/4;" :col 4 :parent "HREAD")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1455)
	       (:type "constant_declaration" :desc "    constant pad : INTEGER := ne*4 - VALUE'length;" :col 4 :parent "HREAD")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 1456)
	       (:type "variable_declaration" :desc "    variable sv  : STD_ULOGIC_VECTOR(0 to ne*4 - 1);" :col 4 :parent "HREAD")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1457)
	       (:type "variable_declaration" :desc "    variable i   : INTEGER;" :col 4 :parent "HREAD")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1458)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "HREAD")
	       ("HREAD" :file "../files/common/std_logic_1164-body.vhdl" :line 1450)
	       (:type "procedure_body" :desc "  procedure HREAD (L    : inout LINE; VALUE : out STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("ok" :file "../files/common/std_logic_1164-body.vhdl" :line 1505)
	       (:type "variable_declaration" :desc "    variable ok  : BOOLEAN;" :col 4 :parent "HREAD")
	       ("c" :file "../files/common/std_logic_1164-body.vhdl" :line 1506)
	       (:type "variable_declaration" :desc "    variable c   : CHARACTER;" :col 4 :parent "HREAD")
	       ("ne" :file "../files/common/std_logic_1164-body.vhdl" :line 1507)
	       (:type "constant_declaration" :desc "    constant ne  : INTEGER := (VALUE'length+3)/4;" :col 4 :parent "HREAD")
	       ("pad" :file "../files/common/std_logic_1164-body.vhdl" :line 1508)
	       (:type "constant_declaration" :desc "    constant pad : INTEGER := ne*4 - VALUE'length;" :col 4 :parent "HREAD")
	       ("sv" :file "../files/common/std_logic_1164-body.vhdl" :line 1509)
	       (:type "variable_declaration" :desc "    variable sv  : STD_ULOGIC_VECTOR(0 to ne*4 - 1);" :col 4 :parent "HREAD")
	       ("i" :file "../files/common/std_logic_1164-body.vhdl" :line 1510)
	       (:type "variable_declaration" :desc "    variable i   : INTEGER;" :col 4 :parent "HREAD")
	       ("lastu" :file "../files/common/std_logic_1164-body.vhdl" :line 1511)
	       (:type "variable_declaration" :desc "    variable lastu  : BOOLEAN := false;       -- last character was an \"_\"" :col 4 :parent "HREAD")
	       ("HREAD" :file "../files/common/std_logic_1164-body.vhdl" :line 1504)
	       (:type "procedure_body" :desc "  procedure HREAD (L : inout LINE; VALUE : out STD_ULOGIC_VECTOR) is" :col 2 :parent "std_logic_1164")
	       ("VALUE" :file "../files/common/std_logic_1164-body.vhdl" :line 1560)
	       (:type "constant_interface_declaration" :desc "  procedure OWRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 44 :parent "OWRITE")
	       ("JUSTIFIED" :file "../files/common/std_logic_1164-body.vhdl" :line 1561)
	       (:type "constant_interface_declaration" :desc "                    JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 20 :parent "OWRITE")
	       ("FIELD" :file "../files/common/std_logic_1164-body.vhdl" :line 1561)
	       (:type "constant_interface_declaration" :desc "                    JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 53 :parent "OWRITE")
	       ("OWRITE" :file "../files/common/std_logic_1164-body.vhdl" :line 1560)
	       (:type "procedure_body" :desc "  procedure OWRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("VALUE" :file "../files/common/std_logic_1164-body.vhdl" :line 1566)
	       (:type "constant_interface_declaration" :desc "  procedure HWRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 44 :parent "HWRITE")
	       ("JUSTIFIED" :file "../files/common/std_logic_1164-body.vhdl" :line 1567)
	       (:type "constant_interface_declaration" :desc "                    JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 20 :parent "HWRITE")
	       ("FIELD" :file "../files/common/std_logic_1164-body.vhdl" :line 1567)
	       (:type "constant_interface_declaration" :desc "                    JUSTIFIED : in    SIDE := right; FIELD : in WIDTH := 0) is" :col 53 :parent "HWRITE")
	       ("HWRITE" :file "../files/common/std_logic_1164-body.vhdl" :line 1566)
	       (:type "procedure_body" :desc "  procedure HWRITE (L         : inout LINE; VALUE : in STD_ULOGIC_VECTOR;" :col 2 :parent "std_logic_1164")
	       ("std_logic_1164" :file "../files/common/std_logic_1164-body.vhdl" :line 54)
	       (:type "package_body" :desc "package body std_logic_1164 is" :col 0 :parent nil)))
