#s(hash-table test equal data
	      (("tb_axi_if_converter" :file "../files/common/tb_axi_if_converter.vhd" :line 13)
	       (:type "entity_declaration" :desc "entity tb_axi_if_converter is" :col 0 :parent nil)
	       ("C_S_AXI_DATA_WIDTH" :file "../files/common/tb_axi_if_converter.vhd" :line 20)
	       (:type "constant_declaration" :desc "    constant C_S_AXI_DATA_WIDTH : integer := 32;" :col 4 :parent "TB")
	       ("C_S_AXI_ADDR_WIDTH" :file "../files/common/tb_axi_if_converter.vhd" :line 21)
	       (:type "constant_declaration" :desc "    constant C_S_AXI_ADDR_WIDTH : integer := 7;" :col 4 :parent "TB")
	       ("clk" :file "../files/common/tb_axi_if_converter.vhd" :line 24)
	       (:type "signal_declaration" :desc "    signal clk        : std_logic := '1';" :col 4 :parent "TB")
	       ("resetn" :file "../files/common/tb_axi_if_converter.vhd" :line 25)
	       (:type "signal_declaration" :desc "    signal resetn     : std_logic := '0';" :col 4 :parent "TB")
	       ("clk_fs_ext" :file "../files/common/tb_axi_if_converter.vhd" :line 26)
	       (:type "signal_declaration" :desc "    signal clk_fs_ext : std_logic := '1';" :col 4 :parent "TB")
	       ("s_axi_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 28)
	       (:type "signal_declaration" :desc "    signal s_axi_aclk    : std_logic := '1';" :col 4 :parent "TB")
	       ("s_axi_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 29)
	       (:type "signal_declaration" :desc "    signal s_axi_aresetn : std_logic := '0';" :col 4 :parent "TB")
	       ("s_axi_awaddr" :file "../files/common/tb_axi_if_converter.vhd" :line 30)
	       (:type "signal_declaration" :desc "    signal s_axi_awaddr  : std_logic_vector(31 downto 0);" :col 4 :parent "TB")
	       ("s_axi_awprot" :file "../files/common/tb_axi_if_converter.vhd" :line 31)
	       (:type "signal_declaration" :desc "    signal s_axi_awprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("s_axi_awvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 32)
	       (:type "signal_declaration" :desc "    signal s_axi_awvalid : std_logic;" :col 4 :parent "TB")
	       ("s_axi_awready" :file "../files/common/tb_axi_if_converter.vhd" :line 33)
	       (:type "signal_declaration" :desc "    signal s_axi_awready : std_logic;" :col 4 :parent "TB")
	       ("s_axi_wdata" :file "../files/common/tb_axi_if_converter.vhd" :line 34)
	       (:type "signal_declaration" :desc "    signal s_axi_wdata   : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("s_axi_wstrb" :file "../files/common/tb_axi_if_converter.vhd" :line 35)
	       (:type "signal_declaration" :desc "    signal s_axi_wstrb   : std_logic_vector((C_S_AXI_DATA_WIDTH/8)-1 downto 0);" :col 4 :parent "TB")
	       ("s_axi_wvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 36)
	       (:type "signal_declaration" :desc "    signal s_axi_wvalid  : std_logic;" :col 4 :parent "TB")
	       ("s_axi_wready" :file "../files/common/tb_axi_if_converter.vhd" :line 37)
	       (:type "signal_declaration" :desc "    signal s_axi_wready  : std_logic;" :col 4 :parent "TB")
	       ("s_axi_bresp" :file "../files/common/tb_axi_if_converter.vhd" :line 38)
	       (:type "signal_declaration" :desc "    signal s_axi_bresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("s_axi_bvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 39)
	       (:type "signal_declaration" :desc "    signal s_axi_bvalid  : std_logic;" :col 4 :parent "TB")
	       ("s_axi_bready" :file "../files/common/tb_axi_if_converter.vhd" :line 40)
	       (:type "signal_declaration" :desc "    signal s_axi_bready  : std_logic;" :col 4 :parent "TB")
	       ("s_axi_araddr" :file "../files/common/tb_axi_if_converter.vhd" :line 41)
	       (:type "signal_declaration" :desc "    signal s_axi_araddr  : std_logic_vector(31 downto 0);" :col 4 :parent "TB")
	       ("s_axi_arprot" :file "../files/common/tb_axi_if_converter.vhd" :line 42)
	       (:type "signal_declaration" :desc "    signal s_axi_arprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("s_axi_arvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 43)
	       (:type "signal_declaration" :desc "    signal s_axi_arvalid : std_logic;" :col 4 :parent "TB")
	       ("s_axi_arready" :file "../files/common/tb_axi_if_converter.vhd" :line 44)
	       (:type "signal_declaration" :desc "    signal s_axi_arready : std_logic;" :col 4 :parent "TB")
	       ("s_axi_rdata" :file "../files/common/tb_axi_if_converter.vhd" :line 45)
	       (:type "signal_declaration" :desc "    signal s_axi_rdata   : std_logic_vector(C_S_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("s_axi_rresp" :file "../files/common/tb_axi_if_converter.vhd" :line 46)
	       (:type "signal_declaration" :desc "    signal s_axi_rresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("s_axi_rvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 47)
	       (:type "signal_declaration" :desc "    signal s_axi_rvalid  : std_logic;" :col 4 :parent "TB")
	       ("s_axi_rready" :file "../files/common/tb_axi_if_converter.vhd" :line 48)
	       (:type "signal_declaration" :desc "    signal s_axi_rready  : std_logic;" :col 4 :parent "TB")
	       ("s_axis_lch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 50)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("s_axis_lch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 51)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("s_axis_lch_tdata" :file "../files/common/tb_axi_if_converter.vhd" :line 52)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_tdata   : std_logic_vector(63 downto 0) := (others => '0');" :col 4 :parent "TB")
	       ("s_axis_lch_tvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 53)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_tvalid  : std_logic;" :col 4 :parent "TB")
	       ("s_axis_lch_tkeep" :file "../files/common/tb_axi_if_converter.vhd" :line 54)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("s_axis_lch_tlast" :file "../files/common/tb_axi_if_converter.vhd" :line 55)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_tlast   : std_logic;" :col 4 :parent "TB")
	       ("s_axis_lch_tready" :file "../files/common/tb_axi_if_converter.vhd" :line 56)
	       (:type "signal_declaration" :desc "    signal s_axis_lch_tready  : std_logic;" :col 4 :parent "TB")
	       ("s_axis_rch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 58)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("s_axis_rch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 59)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("s_axis_rch_tdata" :file "../files/common/tb_axi_if_converter.vhd" :line 60)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_tdata   : std_logic_vector(63 downto 0) := (others => '1');" :col 4 :parent "TB")
	       ("s_axis_rch_tvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 61)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_tvalid  : std_logic;" :col 4 :parent "TB")
	       ("s_axis_rch_tkeep" :file "../files/common/tb_axi_if_converter.vhd" :line 62)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("s_axis_rch_tlast" :file "../files/common/tb_axi_if_converter.vhd" :line 63)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_tlast   : std_logic;" :col 4 :parent "TB")
	       ("s_axis_rch_tready" :file "../files/common/tb_axi_if_converter.vhd" :line 64)
	       (:type "signal_declaration" :desc "    signal s_axis_rch_tready  : std_logic;" :col 4 :parent "TB")
	       ("m_axis_lch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 66)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("m_axis_lch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 67)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("m_axis_lch_tdata" :file "../files/common/tb_axi_if_converter.vhd" :line 68)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tdata   : std_logic_vector(63 downto 0);" :col 4 :parent "TB")
	       ("m_axis_lch_tvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 69)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axis_lch_tkeep" :file "../files/common/tb_axi_if_converter.vhd" :line 70)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axis_lch_tlast" :file "../files/common/tb_axi_if_converter.vhd" :line 71)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axis_lch_tready" :file "../files/common/tb_axi_if_converter.vhd" :line 72)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tready  : std_logic := '1';" :col 4 :parent "TB")
	       ("m_axis_lch_tdest" :file "../files/common/tb_axi_if_converter.vhd" :line 73)
	       (:type "signal_declaration" :desc "    signal m_axis_lch_tdest   : std_logic;" :col 4 :parent "TB")
	       ("m_axis_rch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 75)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("m_axis_rch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 76)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("m_axis_rch_tdata" :file "../files/common/tb_axi_if_converter.vhd" :line 77)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tdata   : std_logic_vector(63 downto 0);" :col 4 :parent "TB")
	       ("m_axis_rch_tvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 78)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axis_rch_tkeep" :file "../files/common/tb_axi_if_converter.vhd" :line 79)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tkeep   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axis_rch_tlast" :file "../files/common/tb_axi_if_converter.vhd" :line 80)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axis_rch_tready" :file "../files/common/tb_axi_if_converter.vhd" :line 81)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tready  : std_logic := '1';" :col 4 :parent "TB")
	       ("m_axis_rch_tdest" :file "../files/common/tb_axi_if_converter.vhd" :line 82)
	       (:type "signal_declaration" :desc "    signal m_axis_rch_tdest   : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 84)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 85)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_awid" :file "../files/common/tb_axi_if_converter.vhd" :line 86)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awid    : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awaddr" :file "../files/common/tb_axi_if_converter.vhd" :line 87)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awaddr  : std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awlen" :file "../files/common/tb_axi_if_converter.vhd" :line 88)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awlen   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awsize" :file "../files/common/tb_axi_if_converter.vhd" :line 89)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awsize  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awburst" :file "../files/common/tb_axi_if_converter.vhd" :line 90)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awburst : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awlock" :file "../files/common/tb_axi_if_converter.vhd" :line 91)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awlock  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_awcache" :file "../files/common/tb_axi_if_converter.vhd" :line 92)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awcache : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awprot" :file "../files/common/tb_axi_if_converter.vhd" :line 93)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awqos" :file "../files/common/tb_axi_if_converter.vhd" :line 94)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awqos   : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awuser" :file "../files/common/tb_axi_if_converter.vhd" :line 95)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awuser  : std_logic_vector(C_M_AXI_AWUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_awvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 96)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_awready" :file "../files/common/tb_axi_if_converter.vhd" :line 97)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_awready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_wdata" :file "../files/common/tb_axi_if_converter.vhd" :line 98)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wdata   : std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_wstrb" :file "../files/common/tb_axi_if_converter.vhd" :line 99)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wstrb   : std_logic_vector(C_M_AXI_DATA_WIDTH/8-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_wlast" :file "../files/common/tb_axi_if_converter.vhd" :line 100)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_wuser" :file "../files/common/tb_axi_if_converter.vhd" :line 101)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wuser   : std_logic_vector(C_M_AXI_WUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_wvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 102)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_wready" :file "../files/common/tb_axi_if_converter.vhd" :line 103)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_wready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_bid" :file "../files/common/tb_axi_if_converter.vhd" :line 104)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_bid     : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_bresp" :file "../files/common/tb_axi_if_converter.vhd" :line 105)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_bresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_buser" :file "../files/common/tb_axi_if_converter.vhd" :line 106)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_buser   : std_logic_vector(C_M_AXI_BUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_bvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 107)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_bvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_bready" :file "../files/common/tb_axi_if_converter.vhd" :line 108)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_bready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_arid" :file "../files/common/tb_axi_if_converter.vhd" :line 109)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arid    : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_araddr" :file "../files/common/tb_axi_if_converter.vhd" :line 110)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_araddr  : std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arlen" :file "../files/common/tb_axi_if_converter.vhd" :line 111)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arlen   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arsize" :file "../files/common/tb_axi_if_converter.vhd" :line 112)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arsize  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arburst" :file "../files/common/tb_axi_if_converter.vhd" :line 113)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arburst : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arlock" :file "../files/common/tb_axi_if_converter.vhd" :line 114)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arlock  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_arcache" :file "../files/common/tb_axi_if_converter.vhd" :line 115)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arcache : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arprot" :file "../files/common/tb_axi_if_converter.vhd" :line 116)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arqos" :file "../files/common/tb_axi_if_converter.vhd" :line 117)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arqos   : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_aruser" :file "../files/common/tb_axi_if_converter.vhd" :line 118)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_aruser  : std_logic_vector(C_M_AXI_ARUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_arvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 119)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_arready" :file "../files/common/tb_axi_if_converter.vhd" :line 120)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_arready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_rid" :file "../files/common/tb_axi_if_converter.vhd" :line 121)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rid     : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_rdata" :file "../files/common/tb_axi_if_converter.vhd" :line 122)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rdata   : std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_rresp" :file "../files/common/tb_axi_if_converter.vhd" :line 123)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_rlast" :file "../files/common/tb_axi_if_converter.vhd" :line 124)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_ruser" :file "../files/common/tb_axi_if_converter.vhd" :line 125)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_ruser   : std_logic_vector(C_M_AXI_RUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_lch_rvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 126)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_lch_rready" :file "../files/common/tb_axi_if_converter.vhd" :line 127)
	       (:type "signal_declaration" :desc "    signal m_axi_lch_rready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 129)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_aclk    : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 130)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_aresetn : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_awid" :file "../files/common/tb_axi_if_converter.vhd" :line 131)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awid    : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awaddr" :file "../files/common/tb_axi_if_converter.vhd" :line 132)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awaddr  : std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awlen" :file "../files/common/tb_axi_if_converter.vhd" :line 133)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awlen   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awsize" :file "../files/common/tb_axi_if_converter.vhd" :line 134)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awsize  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awburst" :file "../files/common/tb_axi_if_converter.vhd" :line 135)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awburst : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awlock" :file "../files/common/tb_axi_if_converter.vhd" :line 136)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awlock  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_awcache" :file "../files/common/tb_axi_if_converter.vhd" :line 137)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awcache : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awprot" :file "../files/common/tb_axi_if_converter.vhd" :line 138)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awqos" :file "../files/common/tb_axi_if_converter.vhd" :line 139)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awqos   : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awuser" :file "../files/common/tb_axi_if_converter.vhd" :line 140)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awuser  : std_logic_vector(C_M_AXI_AWUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_awvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 141)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_awready" :file "../files/common/tb_axi_if_converter.vhd" :line 142)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_awready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_wdata" :file "../files/common/tb_axi_if_converter.vhd" :line 143)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wdata   : std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_wstrb" :file "../files/common/tb_axi_if_converter.vhd" :line 144)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wstrb   : std_logic_vector(C_M_AXI_DATA_WIDTH/8-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_wlast" :file "../files/common/tb_axi_if_converter.vhd" :line 145)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_wuser" :file "../files/common/tb_axi_if_converter.vhd" :line 146)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wuser   : std_logic_vector(C_M_AXI_WUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_wvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 147)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_wready" :file "../files/common/tb_axi_if_converter.vhd" :line 148)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_wready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_bid" :file "../files/common/tb_axi_if_converter.vhd" :line 149)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_bid     : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_bresp" :file "../files/common/tb_axi_if_converter.vhd" :line 150)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_bresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_buser" :file "../files/common/tb_axi_if_converter.vhd" :line 151)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_buser   : std_logic_vector(C_M_AXI_BUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_bvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 152)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_bvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_bready" :file "../files/common/tb_axi_if_converter.vhd" :line 153)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_bready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_arid" :file "../files/common/tb_axi_if_converter.vhd" :line 154)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arid    : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_araddr" :file "../files/common/tb_axi_if_converter.vhd" :line 155)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_araddr  : std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arlen" :file "../files/common/tb_axi_if_converter.vhd" :line 156)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arlen   : std_logic_vector(7 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arsize" :file "../files/common/tb_axi_if_converter.vhd" :line 157)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arsize  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arburst" :file "../files/common/tb_axi_if_converter.vhd" :line 158)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arburst : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arlock" :file "../files/common/tb_axi_if_converter.vhd" :line 159)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arlock  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_arcache" :file "../files/common/tb_axi_if_converter.vhd" :line 160)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arcache : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arprot" :file "../files/common/tb_axi_if_converter.vhd" :line 161)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arqos" :file "../files/common/tb_axi_if_converter.vhd" :line 162)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arqos   : std_logic_vector(3 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_aruser" :file "../files/common/tb_axi_if_converter.vhd" :line 163)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_aruser  : std_logic_vector(C_M_AXI_ARUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_arvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 164)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_arready" :file "../files/common/tb_axi_if_converter.vhd" :line 165)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_arready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_rid" :file "../files/common/tb_axi_if_converter.vhd" :line 166)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rid     : std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_rdata" :file "../files/common/tb_axi_if_converter.vhd" :line 167)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rdata   : std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_rresp" :file "../files/common/tb_axi_if_converter.vhd" :line 168)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_rlast" :file "../files/common/tb_axi_if_converter.vhd" :line 169)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rlast   : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_ruser" :file "../files/common/tb_axi_if_converter.vhd" :line 170)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_ruser   : std_logic_vector(C_M_AXI_RUSER_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_rch_rvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 171)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_rch_rready" :file "../files/common/tb_axi_if_converter.vhd" :line 172)
	       (:type "signal_declaration" :desc "    signal m_axi_rch_rready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_aclk" :file "../files/common/tb_axi_if_converter.vhd" :line 174)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_aclk    : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_aresetn" :file "../files/common/tb_axi_if_converter.vhd" :line 175)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_aresetn : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_awaddr" :file "../files/common/tb_axi_if_converter.vhd" :line 176)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_awaddr  : std_logic_vector(C_M_MEM_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_awprot" :file "../files/common/tb_axi_if_converter.vhd" :line 177)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_awprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_awvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 178)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_awvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_awready" :file "../files/common/tb_axi_if_converter.vhd" :line 179)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_awready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_wdata" :file "../files/common/tb_axi_if_converter.vhd" :line 180)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_wdata   : std_logic_vector(C_M_MEM_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_wstrb" :file "../files/common/tb_axi_if_converter.vhd" :line 181)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_wstrb   : std_logic_vector(C_M_MEM_AXI_DATA_WIDTH/8-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_wvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 182)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_wvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_wready" :file "../files/common/tb_axi_if_converter.vhd" :line 183)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_wready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_bresp" :file "../files/common/tb_axi_if_converter.vhd" :line 184)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_bresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_bvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 185)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_bvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_bready" :file "../files/common/tb_axi_if_converter.vhd" :line 186)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_bready  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_araddr" :file "../files/common/tb_axi_if_converter.vhd" :line 187)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_araddr  : std_logic_vector(C_M_MEM_AXI_ADDR_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_arprot" :file "../files/common/tb_axi_if_converter.vhd" :line 188)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_arprot  : std_logic_vector(2 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_arvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 189)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_arvalid : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_arready" :file "../files/common/tb_axi_if_converter.vhd" :line 190)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_arready : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_rdata" :file "../files/common/tb_axi_if_converter.vhd" :line 191)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_rdata   : std_logic_vector(C_M_MEM_AXI_DATA_WIDTH-1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_rresp" :file "../files/common/tb_axi_if_converter.vhd" :line 192)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_rresp   : std_logic_vector(1 downto 0);" :col 4 :parent "TB")
	       ("m_axi_conf_rvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 193)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_rvalid  : std_logic;" :col 4 :parent "TB")
	       ("m_axi_conf_rready" :file "../files/common/tb_axi_if_converter.vhd" :line 194)
	       (:type "signal_declaration" :desc "    signal m_axi_conf_rready  : std_logic;" :col 4 :parent "TB")
	       ("s_bfm_in_r" :file "../files/common/tb_axi_if_converter.vhd" :line 198)
	       (:type "signal_declaration" :desc "    signal s_bfm_in_r  : s_common_response_r_in;" :col 4 :parent "TB")
	       ("s_bfm_out_r" :file "../files/common/tb_axi_if_converter.vhd" :line 199)
	       (:type "signal_declaration" :desc "    signal s_bfm_out_r : s_common_response_r_out;" :col 4 :parent "TB")
	       ("s_bfm_in_w" :file "../files/common/tb_axi_if_converter.vhd" :line 200)
	       (:type "signal_declaration" :desc "    signal s_bfm_in_w  : s_common_response_w_in;" :col 4 :parent "TB")
	       ("s_bfm_out_w" :file "../files/common/tb_axi_if_converter.vhd" :line 201)
	       (:type "signal_declaration" :desc "    signal s_bfm_out_w : s_common_response_w_out;" :col 4 :parent "TB")
	       ("m_bfm_in_r" :file "../files/common/tb_axi_if_converter.vhd" :line 204)
	       (:type "signal_declaration" :desc "    signal m_bfm_in_r  : m_common_response_r_type_in;" :col 4 :parent "TB")
	       ("m_bfm_out_r" :file "../files/common/tb_axi_if_converter.vhd" :line 205)
	       (:type "signal_declaration" :desc "    signal m_bfm_out_r : m_common_response_r_type_out;" :col 4 :parent "TB")
	       ("m_bfm_in_w" :file "../files/common/tb_axi_if_converter.vhd" :line 206)
	       (:type "signal_declaration" :desc "    signal m_bfm_in_w  : m_common_response_w_type_in;" :col 4 :parent "TB")
	       ("m_bfm_out_w" :file "../files/common/tb_axi_if_converter.vhd" :line 207)
	       (:type "signal_declaration" :desc "    signal m_bfm_out_w : m_common_response_w_type_out;" :col 4 :parent "TB")
	       ("stop_clock" :file "../files/common/tb_axi_if_converter.vhd" :line 210)
	       (:type "signal_declaration" :desc "    signal stop_clock : std_logic := '0';" :col 4 :parent "TB")
	       ("init_values" :file "../files/common/tb_axi_if_converter.vhd" :line 531)
	       (:type "procedure_body" :desc "        procedure init_values is" :col 8 :parent "TB")
	       ("tvalid" :file "../files/common/tb_axi_if_converter.vhd" :line 540)
	       (:type "signal_interface_declaration" :desc "        procedure rx_data (signal tvalid : out std_logic; signal tdata : inout std_logic_vector(63 downto 0); constant RX_DATA_AMOUNT : natural := 128) is" :col 27 :parent "rx_data")
	       ("tdata" :file "../files/common/tb_axi_if_converter.vhd" :line 540)
	       (:type "signal_interface_declaration" :desc "        procedure rx_data (signal tvalid : out std_logic; signal tdata : inout std_logic_vector(63 downto 0); constant RX_DATA_AMOUNT : natural := 128) is" :col 58 :parent "rx_data")
	       ("RX_DATA_AMOUNT" :file "../files/common/tb_axi_if_converter.vhd" :line 540)
	       (:type "constant_interface_declaration" :desc "        procedure rx_data (signal tvalid : out std_logic; signal tdata : inout std_logic_vector(63 downto 0); constant RX_DATA_AMOUNT : natural := 128) is" :col 110 :parent "rx_data")
	       ("rx_data" :file "../files/common/tb_axi_if_converter.vhd" :line 540)
	       (:type "procedure_body" :desc "        procedure rx_data (signal tvalid : out std_logic; signal tdata : inout std_logic_vector(63 downto 0); constant RX_DATA_AMOUNT : natural := 128) is" :col 8 :parent "TB")
	       ("TB" :file "../files/common/tb_axi_if_converter.vhd" :line 18)
	       (:type "architecture_body" :desc "architecture TB of tb_axi_if_converter is" :col 0 :parent nil)))
